-- standard_oicr_config
--StartNoTest
-- Standard values for an OICR MISO instance

INSERT INTO BoxSize (`rows`, `columns`, scannable) VALUES
  (8,12,true),
  (10,10,false);

INSERT INTO BoxUse (alias) VALUES
  ('DNA'),
  ('RNA'),
  ('Tissue'),
  ('Sequencing'),
  ('Plate');

INSERT INTO `LibraryType` (description, platformType) VALUES
  ('cDNA', 'PacBio'),
  ('Amplicon', 'PacBio'),
  ('2kb Shotgun', 'PacBio'),
  ('10kb Shotgun', 'PacBio'),
  ('20kb Shotgun', 'PacBio'),
  ('Plasmid', 'PacBio'),
  ('BAC', 'PacBio');

INSERT INTO KitDescriptor
  (name, version, manufacturer, partNumber, stockLevel, kitType, platformType, description) VALUES
  ('V4 PE Cluster Kit', 1, 'Illumina', 'PE-401-4001', 4, 'Sequencing', 'Illumina', '(Box 1 of 2): 4 & (Box 2 of 2): 4 & (V4 Flowcells): 4'),
  ('MiSeq Reagent Kit 300 Cycle', 1, 'Illumina', 'MS-102-2002', 4, 'Sequencing', 'Illumina', '(Box 1 of 2): 4 & (Box 2 of 2): 7'),
  ('SBS Reagent Kit 250 Cycle', 1, 'Illumina', 'FC-401-4003', 4, 'Sequencing', 'Illumina', '(Box 1 of 2): 4 & (Box 2 of 2): 4'),
  ('Rapid V2 PE Cluster Kit', 1, 'Illumina', 'PE-402-4002', 2, 'Clustering', 'Illumina', '(Cluster Kits): 2 & (Rapid V2 Flowcells): 2'),
  ('Rapid V2 SBS Reagent Kit 200 Cycle', 1, 'Illumina', 'FC-402-4021', 1, 'Sequencing', 'Illumina', '(Box 1 of 2): 1 & (Box 2 of 2): 1'),
  ('Rapid V2 SBS Reagent Kit 50 Cycle', 1, 'Illumina', 'FC-402-4022', 2, 'Sequencing', 'Illumina', '(Box 1 of 2): 2 & (Box 2 of 2): 2'),
  ('HiSeq Rapid Duo cBot Sample Plate Box', 1, 'Illumina', 'n/a', 2, 'Clustering', 'Illumina', 'n/a'),
  ('TruSeq RapidRun Duo cBot', 1, 'Illumina', 'CT-402-4001', 1, 'Clustering', 'Illumina', 'Expired'),
  ('SR Rapid Cluster Kit', 1, 'Illumina', 'GD-401-3001', 1, 'Clustering', 'Illumina', 'Expired (Cluster Kit): 1 & (SR Rapid Flowcells): 1'),
  ('Rapid PE Cluster Kit', 1, 'Illumina', 'GD-402-4001', 4, 'Clustering', 'Illumina', 'Expired. (Cluster Kit): 4 & (Rapid Flowcells): 6'),
  ('V3 PE Cluster Kit', 1, 'Illumina', 'PE-401-3001', 7, 'Clustering', 'Illumina', '(Box 1 of 2): 10 & (Box 2 of 2): 7 & (V3 Flowcells): 14 (Truseq Multiplex Seq Primer): 13'),
  ('SBS Rapid Run Kits - 200 Cycle', 1, 'Illumina', 'FC-402-4001', 7, 'Sequencing', 'Illumina', 'Expired'),
  ('SBS Rapid Run Kits - 50 Cycle', 1, 'Illumina', 'FC-402-4002', 1, 'Sequencing', 'Illumina', 'Expired'),
  ('SBS Reagent Kit 200 Cycle', 1, 'Illumina', 'FC-401-3001', 5, 'Sequencing', 'Illumina', '(Box 1 of 2): 9 & (Box 2 of 2): 5. Box 1 - 5 expired. Box 2 - 2 expired'),
  ('Rapid V2 SBS Reagent Kit 500 cycle', 1, 'Illumina', 'FC-402-4023', 1, 'Sequencing', 'Illumina', '(Box 1 of 2): 1 & (Box 2 of 2): 1'),
  ('Rapid Duo cBot Sample Plate Box', 1, 'Illumina', 'n/a', 2, 'Clustering', 'Illumina', 'n/a'),
  ('MiSeq Reagent Kit 50 Cycle', 1, 'Illumina', 'MS-102-2001', 0, 'Sequencing', 'Illumina', '(Box 1 of 2): 0 & (Box 2 of 2): 9'),
  ('MiSeq Reagent Kit 500 cycle', 1, 'Illumina', 'MS-102-2003', 1, 'Sequencing', 'Illumina', '(Box 1 of 2): 1--Expired & (Box 2 of 2): 11'),
  ('Dual Index Seq. Primer Paired End', 1, 'Illumina', 'PE-121-1003', 14, 'Sequencing', 'Illumina', 'n/a'),
  ('Dual Index Seq. Primer Single End', 1, 'Illumina', 'FC-121-1003', 2, 'Sequencing', 'Illumina', 'All Expired'),
  ('MiSeq Reagent Kit 600 Cycle (V3)', 1, 'Illumina', 'MS-102-3003', 1, 'Sequencing', 'Illumina', '(Box 1 of 2): 1--Expired & (Box 2 of 2): 1'),
  ('SR Cluster Kit', 1, 'Illumina', 'GD-401-4001', 1, 'Sequencing', 'Illumina', '(Cluster Kit): 1-Expired & (SR Flowcells): 2'),
  ('HiSeq Rehyb V4', 1, 'Illumina', 'GD-403-4001', 4, 'Sequencing', 'Illumina', '4 Expired'),
  ('Multiprimer Re-hybridization Plate', 1, 'Illumina', 'GD-305-1001', 3, 'Sequencing', 'Illumina', '3 Expired'),
  ('Agilent SureSelect XT', '0', 'Agilent', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('Agilent SureSelect XT2', '0', 'Agilent', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('AmpliSeq-Illumina Exome V1', '1', 'AmpliSeq', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('AmpliSeq-Illumina V1', '1', 'AmpliSeq', '1', '0', 'Library', 'Illumina', 'AmpliSeq-Illumina Modified Protocol Version 1'),
  ('AmpliSeq-KAPA Hyper Prep V1', '1', 'AmpliSeq', '1', '0', 'Library', 'Illumina', 'Testing'),
  ('GA_PE', '0', 'GA', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('GA_TruSeq_SmRNA', '0', 'GA', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('KAPA BC OnBead', '0', 'KAPA', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('KAPA Hyper Prep', '0', 'KAPA', '1', '0', 'Library', 'Illumina', 'KK8504 With KAPA Library Amplification Primer Mix (10X 96 reactions)'),
  ('Nextera DNA', '0', 'Nextera', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('Thunderbolt Cancer Panel', '0', 'Thunderbolt', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('TruSeq Amplicon - Cancer Panel', '0', 'TruSeq', '1', '0', 'Library', 'Illumina', 'Associated with Illumina PE libraries. Not compatible with the HiSeq - only MiSeq'),
  ('TruSeq RNA Access', '0', 'TruSeq', 'RS-301-2001', '0', 'Library', 'Illumina', 'RS-301-2001'),
  ('TruSeq_Stranded_mRNA', '0', 'TruSeq', '1', '0', 'Library', 'Illumina', 'Illumina Directional mRNA Library'),
  ('TruSeq_Stranded_TotalRNA', '0', 'TruSeq', '1', '0', 'Library', 'Illumina', 'Illumina Directional Whole Transcriptome Library');

INSERT INTO TagBarcodeFamily(platformType, name) VALUES
  ('ILLUMINA', 'Agilent'),
  ('ILLUMINA', 'Illumina 6bp'),
  ('ILLUMINA', 'NEXTflex 6bp'),
  ('ILLUMINA', 'NEXTflex 8bp'),
  ('ILLUMINA', 'Nextera'),
  ('ILLUMINA', 'RBC1'),
  ('ILLUMINA', 'SureSelect XT2'),
  ('ILLUMINA', 'TCRindex2'),
  ('ILLUMINA', 'TruSeq smRNA');

INSERT INTO TagBarcodes (name, sequence, position, tagFamilyId) VALUES
  ('Index 01', 'AACGTGAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 02', 'AAACATCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 03', 'ATGCCTAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 04', 'AGTGGTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 05', 'ACCACTGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 06', 'ACATTGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 07', 'CAGATCTG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 08', 'CATCAAGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 09', 'CGCTGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 10', 'ACAAGCTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 11', 'CTGTAGCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 12', 'AGTACAAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 13', 'AACAACCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 14', 'AACCGAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 15', 'AACGCTTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 16', 'AAGACGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 17', 'AAGGTACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 18', 'ACACAGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 19', 'ACAGCAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 20', 'ACCTCCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 21', 'ACGCTCGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 22', 'ACGTATCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 23', 'ACTATGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 24', 'AGAGTCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 25', 'AGATCGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 26', 'AGCAGGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 27', 'AGTCACTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 28', 'ATCCTGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 29', 'ATTGAGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 30', 'CAACCACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 31', 'GACTAGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 32', 'CAATGGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 33', 'CACTTCGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 34', 'CAGCGTTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 35', 'CATACCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 36', 'CCAGTTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 37', 'CCGAAGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 38', 'CCGTGAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 39', 'CCTCCTGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 40', 'CGAACTTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 41', 'CGACTGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 42', 'CGCATACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 43', 'CTCAATGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 44', 'CTGAGCCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 45', 'CTGGCATA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 46', 'GAATCTGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 47', 'CAAGACTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 48', 'GAGCTGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 49', 'GATAGACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 50', 'GCCACATA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 51', 'GCGAGTAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 52', 'GCTAACGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 53', 'GCTCGGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 54', 'GGAGAACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 55', 'GGTGCGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 56', 'GTACGCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 57', 'GTCGTAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 58', 'GTCTGTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 59', 'GTGTTCTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 60', 'TAGGATGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 61', 'TATCAGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 62', 'TCCGTCTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 63', 'TCTTCACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 64', 'TGAAGAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 65', 'TGGAACAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 66', 'TGGCTTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 67', 'TGGTGGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 68', 'TTCACGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 69', 'AACTCACC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 70', 'AAGAGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 71', 'AAGGACAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 72', 'AATCCGTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 73', 'AATGTTGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 74', 'ACACGACC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 75', 'ACAGATTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 76', 'AGATGTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 77', 'AGCACCTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 78', 'AGCCATGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 79', 'AGGCTAAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 80', 'ATAGCGAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 81', 'ATCATTCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 82', 'ATTGGCTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 83', 'CAAGGAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 84', 'CACCTTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 85', 'CCATCCTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 86', 'CCGACAAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 87', 'CCTAATCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 88', 'CCTCTATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 89', 'CGACACAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 90', 'CGGATTGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 91', 'CTAAGGTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 92', 'GAACAGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 93', 'GACAGTGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 94', 'GAGTTAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 95', 'GATGAATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('Index 96', 'GCCAAGAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 8bp')),
  ('S501', 'TAGATCGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('S502', 'CTCTCTAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('S503', 'TATCCTCT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('S504', 'AGAGTAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('S505', 'GTAAGGAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('S506', 'ACTGCATA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('S507', 'AAGGAGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('S508', 'CTAAGCCT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N701', 'TAAGGCGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N702', 'CGTACTAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N703', 'AGGCAGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N704', 'TCCTGAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N705', 'GGACTCCT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N706', 'TAGGCATG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N707', 'CTCTCTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N708', 'CAGAGAGG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N709', 'GCTACGCT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N710', 'CGAGGCTG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N711', 'AAGAGGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('N712', 'GTAGAGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Nextera')),
  ('BC1', 'ATCCGTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC2', 'GTTCACAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC3', 'TGCTACGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC4', 'AGACTCAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC5', 'ATCCAAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC6', 'CGCATTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC7', 'ATGACACG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC8', 'AACTACGG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC9', 'GAGGCTTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC10', 'GACTTCGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC11', 'GTCGTTGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC12', 'TCTGCTTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC13', 'GAGGACTT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC14', 'TCCTCGAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC15', 'AAGCAGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC16', 'TTCTAGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC17', 'GCGTAACT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC18', 'GTGATCCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC19', 'GTGCAGTT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC20', 'GACCGTAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC21', 'TGATCGTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC22', 'GTTCAAGG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC23', 'CCATTCGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('BC24', 'AGTATGCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'RBC1')),
  ('Index 01', 'ATCACG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 02', 'CGATGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 03', 'TTAGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 04', 'TGACCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 05', 'ACAGTG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 06', 'GCCAAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 07', 'CAGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 08', 'ACTTGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 09', 'GATCAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 10', 'TAGCTT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 11', 'GGCTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 12', 'CTTGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 13', 'AGTCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 14', 'AGTTCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 15', 'ATGTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 16', 'CCGTCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 17', 'GTAGAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 18', 'GTCCGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 19', 'GTGAAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 20', 'GTGGCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 21', 'GTTTCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 22', 'CGTACG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 23', 'GAGTGG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 24', 'GGTAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 25', 'ACTGAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 26', 'ATGAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 27', 'ATTCCT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 28', 'CAAAAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 29', 'CAACTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 30', 'CACCGG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 31', 'CACGAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 32', 'CACTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 33', 'CAGGCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 34', 'CATGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 35', 'CATTTT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 36', 'CCAACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 37', 'CGGAAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 38', 'CTAGCT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 39', 'CTATAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 40', 'CTCAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 41', 'GACGAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 42', 'TAATCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 43', 'TACAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 44', 'TATAAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 45', 'TCATTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 46', 'TCCCGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 47', 'TCGAAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 48', 'TCGGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('None', '', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Illumina 6bp')),
  ('Index 01', 'AACGTGAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 02', 'AAACATCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 03', 'ATGCCTAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 04', 'AGTGGTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 05', 'ACCACTGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 06', 'ACATTGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 07', 'CAGATCTG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 08', 'CATCAAGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 09', 'CGCTGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 10', 'ACAAGCTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 11', 'CTGTAGCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 12', 'AGTACAAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 13', 'AACAACCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 14', 'AACCGAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 15', 'AACGCTTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 16', 'AAGACGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 17', 'AAGGTACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 18', 'ACACAGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 19', 'ACAGCAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 20', 'ACCTCCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 21', 'ACGCTCGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 22', 'ACGTATCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 23', 'ACTATGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 24', 'AGAGTCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 25', 'AGATCGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 26', 'AGCAGGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 27', 'AGTCACTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 28', 'ATCCTGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 29', 'ATTGAGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 30', 'CAACCACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 31', 'CAAGACTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 32', 'CAATGGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 33', 'CACTTCGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 34', 'CAGCGTTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 35', 'CATACCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 36', 'CCAGTTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 37', 'CCGAAGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 38', 'CCGTGAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 39', 'CCTCCTGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 40', 'CGAACTTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 41', 'CGACTGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 42', 'CGCATACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 43', 'CTCAATGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 44', 'CTGAGCCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 45', 'CTGGCATA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 46', 'GAATCTGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 47', 'GACTAGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 48', 'GAGCTGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 49', 'GATAGACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 50', 'GCCACATA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 51', 'GCGAGTAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 52', 'GCTAACGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 53', 'GCTCGGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 54', 'GGAGAACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 55', 'GGTGCGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 56', 'GTACGCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 57', 'GTCGTAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 58', 'GTCTGTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 59', 'GTGTTCTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 60', 'TAGGATGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 61', 'TATCAGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 62', 'TCCGTCTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 63', 'TCTTCACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 64', 'TGAAGAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 65', 'TGGAACAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 66', 'TGGCTTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 67', 'TGGTGGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 68', 'TTCACGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 69', 'AACTCACC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 70', 'AAGAGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 71', 'AAGGACAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 72', 'AATCCGTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 73', 'AATGTTGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 74', 'ACACGACC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 75', 'ACAGATTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 76', 'AGATGTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 77', 'AGCACCTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 78', 'AGCCATGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 79', 'AGGCTAAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 80', 'ATAGCGAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 81', 'ATCATTCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 82', 'ATTGGCTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 83', 'CAAGGAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 84', 'CACCTTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 85', 'CCATCCTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 86', 'CCGACAAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 87', 'CCTAATCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 88', 'CCTCTATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 89', 'CGACACAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 90', 'CGGATTGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 91', 'CTAAGGTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 92', 'GAACAGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 93', 'GACAGTGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 94', 'GAGTTAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 95', 'GATGAATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('Index 96', 'GCCAAGAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'Agilent')),
  ('BC1', 'ATCACG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC2', 'CGATGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC3', 'TTAGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC4', 'TGACCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC5', 'ACAGTG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC6', 'GCCAAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC7', 'CAGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC8', 'ACTTGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC9', 'GATCAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC10', 'TAGCTT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC11', 'GGCTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC12', 'CTTGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC13', 'AGTCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC14', 'AGTTCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC15', 'ATGTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC16', 'CCGTCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC17', 'GTAGAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC18', 'GTCCGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC19', 'GTGAAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC20', 'GTGGCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC21', 'GTTTCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC22', 'CGTACG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC23', 'GAGTGG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('BC24', 'GGTAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TruSeq smRNA')),
  ('Index 1', 'ATCGATCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TCRindex2')),
  ('Index 2', 'TCGATCGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TCRindex2')),
  ('Index 3', 'CGATCGAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TCRindex2')),
  ('Index 4', 'GATCGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'TCRindex2')),
  ('A01', 'ATGCCTAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A02', 'AGCAGGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A03', 'ATCATTCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A04', 'AACTCACC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A05', 'AACGCTTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A06', 'AGCCATGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A07', 'ACGTATCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A08', 'CAGCGTTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A09', 'CTCAATGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A10', 'AATGTTGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A11', 'CCAGTTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('A12', 'CAAGGAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B01', 'GAATCTGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B02', 'GAGCTGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B03', 'GCCACATA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B04', 'GCTAACGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B05', 'GGAGAACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B06', 'GTACGCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B07', 'GTCTGTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B08', 'TAGGATGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B09', 'TCCGTCTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B10', 'TGAAGAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B11', 'TGGCTTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('B12', 'TTCACGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C01', 'AACGTGAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C02', 'AAACATCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C03', 'ACCACTGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C04', 'CAGATCTG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C05', 'CATCAAGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C06', 'AGTACAAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C07', 'CTAAGGTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C08', 'AGTGGTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C09', 'AGGCTAAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C10', 'AGATCGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C11', 'CGACTGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('C12', 'CACCTTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D01', 'CACTTCGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D02', 'GAGTTAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D03', 'CTGGCATA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D04', 'ATCCTGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D05', 'AAGGTACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D06', 'ACATTGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D07', 'CGACACAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D08', 'ACAGCAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D09', 'CCATCCTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D10', 'AAGAGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D11', 'CAAGACTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('D12', 'AAGACGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E01', 'GCCAAGAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E02', 'CGAACTTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E03', 'ACCTCCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E04', 'CTGTAGCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E05', 'CGCTGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E06', 'ATTGAGGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E07', 'CCGTGAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E08', 'CATACCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E09', 'AGATGTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E10', 'CAACCACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E11', 'CCTCCTGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('E12', 'ACACAGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F01', 'GACTAGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F02', 'GATAGACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F03', 'GCGAGTAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F04', 'GCTCGGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F05', 'GGTGCGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F06', 'GTCGTAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F07', 'GTGTTCTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F08', 'TATCAGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F09', 'TCTTCACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F10', 'TGGAACAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F11', 'TGGTGGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('F12', 'GAACAGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G01', 'ATTGGCTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G02', 'AAGGACAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G03', 'ACTATGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G04', 'ACACGACC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G05', 'CCTAATCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G06', 'AGAGTCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G07', 'CAATGGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G08', 'ATAGCGAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G09', 'CCGAAGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G10', 'CCTCTATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G11', 'AACAACCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('G12', 'AACCGAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H01', 'GATGAATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H02', 'GACAGTGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H03', 'CGGATTGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H04', 'AGTCACTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H05', 'CTGAGCCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H06', 'CCGACAAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H07', 'AGCACCTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H08', 'ACGCTCGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H09', 'CGCATACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H10', 'ACAGATTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H11', 'AATCCGTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('H12', 'ACAAGCTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'SureSelect XT2')),
  ('Index 01', 'CGATGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 02', 'TGACCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 03', 'ACAGTG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 04', 'GCCAAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 05', 'CAGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 06', 'CTTGTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 07', 'ATCACG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 08', 'TTAGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 09', 'ACTTGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 10', 'GATCAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 11', 'TAGCTT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 12', 'GGCTAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 13', 'AGTCAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 14', 'AGTTCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 15', 'ATGTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 16', 'CCGTCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 17', 'GTAGAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 18', 'GTCCGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 19', 'GTGAAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 20', 'GTGGCC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 21', 'GTTTCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 22', 'CGTACG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 23', 'GAGTGG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 24', 'GGTAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 25', 'ACTGAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 26', 'ATGAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 27', 'ATTCCT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 28', 'CAAAAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 29', 'CAACTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 30', 'CACCGG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 31', 'CACGAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 32', 'CACTCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 33', 'CAGGCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 34', 'CATGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 35', 'CATTTT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 36', 'CCAACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 37', 'CGGAAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 38', 'CTAGCT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 39', 'CTATAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 40', 'CTCAGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 41', 'GCGCTA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 42', 'TAATCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 43', 'TACAGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 44', 'TATAAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 45', 'TCATTC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 46', 'TCCCGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 47', 'TCGAAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp')),
  ('Index 48', 'TCGGCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'NEXTflex 6bp'));

INSERT INTO QCType (name, description, qcTarget, units) VALUES
  ('Bioanalyzer', 'Measures size of library, including adapters', 'Pool', 'bp'),
  ('qPCR', 'Quantitative PCR', 'Pool', 'mol/&#181;l'),
  ('Tape Station', 'Measures size of library, including adapters', 'Library', 'bp'),
  ('Tape Station', 'Measures size of library, including adapters', 'Pool', 'bp'),
  ('FFPE qPCR', 'Quantitation of FFPE tissue quality', 'Sample', 'Q-ratio'),
  ('Volume Check', 'Measures volume in sample', 'Sample', 'uL'),
  ('Mouse qPCR', 'Measures amount of mouse tissue in sample', 'Sample', '&#37;'),
  ('STR', 'Compares identity of sample against reference', 'Sample', ''),
  ('qcGel', 'Older metric', 'Sample', ''),
  ('RIN', 'RNA Integrity Number', 'Sample', ''),
  ('DV200', 'RNA Integrity Number', 'Sample', '&#37;'),
  ('small RNA &#37;', 'Percentage of small RNA in sample', 'Sample', '&#37;'),
  ('DNAse Treated', 'Yes/No', 'Sample', ''),
  ('Nanodrop', 'For when sample is suspected of contamination', 'Sample', 'ng/&#181;l');

INSERT INTO TissueOrigin (alias, description, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('Ad','Adipose',1,NOW(),1,NOW()),
  ('Ap','Appendix',1,NOW(),1,NOW()),
  ('Ag','Adrenal Gland',1,NOW(),1,NOW()),
  ('Bm','Bone Marrow',1,NOW(),1,NOW()),
  ('Bn','Brain',1,NOW(),1,NOW()),
  ('Br','Breast',1,NOW(),1,NOW()),
  ('Bu','Buccal Cells',1,NOW(),1,NOW()),
  ('Cb','Cord Blood',1,NOW(),1,NOW()),
  ('Cn','Central Nervous System',1,NOW(),1,NOW()),
  ('Du','Duodenum',1,NOW(),1,NOW()),
  ('Es','Esophagus',1,NOW(),1,NOW()),
  ('Fs','Foreskin',1,NOW(),1,NOW()),
  ('Gb','Gallbladder',1,NOW(),1,NOW()),
  ('Hr','Heart',1,NOW(),1,NOW()),
  ('Ki','Kidney',1,NOW(),1,NOW()),
  ('Le','Leukocyte',1,NOW(),1,NOW()),
  ('Li','Large Intestine',1,NOW(),1,NOW()),
  ('Ln','Lymph Node',1,NOW(),1,NOW()),
  ('Lu','Lung',1,NOW(),1,NOW()),
  ('Lv','Liver',1,NOW(),1,NOW()),
  ('Lx','Larynx',1,NOW(),1,NOW()),
  ('Ly','Lymphocyte',1,NOW(),1,NOW()),
  ('Md','Mediastinum',1,NOW(),1,NOW()),
  ('Me','Mesenchyme',1,NOW(),1,NOW()),
  ('Nk','Neck',1,NOW(),1,NOW()),
  ('Oc','Oral Cavity',1,NOW(),1,NOW()),
  ('Om','Omentum',1,NOW(),1,NOW()),
  ('Ov','Ovary',1,NOW(),1,NOW()),
  ('Pa','Pancreas',1,NOW(),1,NOW()),
  ('Pb','Peripheral Blood',1,NOW(),1,NOW()),
  ('Pr','Prostate',1,NOW(),1,NOW()),
  ('Sa','Saliva',1,NOW(),1,NOW()),
  ('Sg','Salivary Gland',1,NOW(),1,NOW()),
  ('Si','Small Intestine',1,NOW(),1,NOW()),
  ('Sk','Skin',1,NOW(),1,NOW()),
  ('Sm','Skeletal Muscle',1,NOW(),1,NOW()),
  ('Sp','Spleen',1,NOW(),1,NOW()),
  ('St','Stomach',1,NOW(),1,NOW()),
  ('Ta','Tail (Referring to Models)',1,NOW(),1,NOW()),
  ('Tr','Trachea',1,NOW(),1,NOW()),
  ('Mu','Muscle',1,NOW(),1,NOW()),
  ('Wm','Worm (Referring to Models)',1,NOW(),1,NOW()),
  ('nn','Unknown',1,NOW(),1,NOW());

INSERT INTO TissueType (alias, description, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('R','Reference or non-tumour, non-diseased tissue sample. Typically used as a donor-specific comparison to a diseased tissue, usually a cancer',1,NOW(),1,NOW()),
  ('P','Primary tumour',1,NOW(),1,NOW()),
  ('M','Metastatic tumour',1,NOW(),1,NOW()),
  ('X','Xenograft derived from some tumour. Note: may not necessarily be a mouse xenograft',1,NOW(),1,NOW()),
  ('T','Unclassifed tumour',1,NOW(),1,NOW()),
  ('C','Cell line derived from a tumour',1,NOW(),1,NOW()),
  ('B','Benign tumour',1,NOW(),1,NOW()),
  ('F','Fibroblast cells',1,NOW(),1,NOW()),
  ('E','Endothelial cells',1,NOW(),1,NOW()),
  ('S','Serum from blood where clotting proteins have been removed',1,NOW(),1,NOW()),
  ('A','Cells taken from Ascites fluid',1,NOW(),1,NOW()),
  ('O','Organoid',1,NOW(),1,NOW());

INSERT INTO TissueMaterial (alias, description, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('Fresh Frozen','Fresh Frozen',1,NOW(),1,NOW()),
  ('FFPE','FFPE',1,NOW(),1,NOW()),
  ('Blood','Blood',1,NOW(),1,NOW());

INSERT INTO SamplePurpose (alias, description, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('CNV','CNV',1,NOW(),1,NOW()),
  ('Extra','Extra',1,NOW(),1,NOW()),
  ('Library','Library',1,NOW(),1,NOW()),
  ('Methylation','Methylation',1,NOW(),1,NOW()),
  ('PacBio','PacBio',1,NOW(),1,NOW()),
  ('Research','Research',1,NOW(),1,NOW()),
  ('Sequenom','Sequenom',1,NOW(),1,NOW()),
  ('Stock','Stock',1,NOW(),1,NOW()),
  ('Validation','Validation',1,NOW(),1,NOW()),
  ('WGA','WGA',1,NOW(),1,NOW());

ALTER TABLE QcPassedDetail MODIFY status BOOLEAN NULL;
INSERT INTO QcPassedDetail (status, description, noteRequired, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  (1,'',0,1,NOW(),1,NOW()),
  (1,'OKd by Collaborator',1,1,NOW(),1,NOW()),
  (NULL,'',0,1,NOW(),1,NOW()),
  (NULL,'Waiting: Path Report',1,1,NOW(),1,NOW()),
  (0,'Failed STR',1,1,NOW(),1,NOW()),
  (0,'Failed Diagnosis',1,1,NOW(),1,NOW()),
  (0,'Failed QC',1,1,NOW(),1,NOW()),
  (0,'Reference Required',0,1,NOW(),1,NOW()),
  (0,'Refused Consent',0,1,NOW(),1,NOW());

INSERT INTO Institute (alias, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('Ontario Institute for Cancer Research',1,NOW(),1,NOW()),
  ('University Health Network',1,NOW(),1,NOW()),
  ('Kingston General Hospital',1,NOW(),1,NOW()),
  ('Massachusetts General Hospital',1,NOW(),1,NOW()),
  ('Mayo Clinic',1,NOW(),1,NOW()),
  ('OPCS',1,NOW(),1,NOW()),
  ('Ottawa Hospital Research Institute',1,NOW(),1,NOW()),
  ('Sheba Medical Center',1,NOW(),1,NOW()),
  ('St Josephs Healthcare Hamilton',1,NOW(),1,NOW()),
  ('St Josephs Health Centre (Toronto)',1,NOW(),1,NOW()),
  ('Sunnybrook Health Sciences Centre',1,NOW(),1,NOW()),
  ('UHN McGill',1,NOW(),1,NOW()),
  ('University of Nebraska Medical Center',1,NOW(),1,NOW());

INSERT INTO Lab (alias, instituteId, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('BioBank', (SELECT instituteId FROM Institute WHERE alias = 'Ontario Institute for Cancer Research'),1,NOW(),1,NOW()),
  ('BioBank', (SELECT instituteId FROM Institute WHERE alias = 'University Health Network'),1,NOW(),1,NOW()),
  ('Brad Wouters', (SELECT instituteId FROM Institute WHERE alias = 'University Health Network'),1,NOW(),1,NOW()),
  ('Catherine OBrien', (SELECT instituteId FROM Institute WHERE alias = 'University Health Network'),1,NOW(),1,NOW()),
  ('John Bell', (SELECT instituteId FROM Institute WHERE alias = 'Ontario Institute for Cancer Research'),1,NOW(),1,NOW()),
  ('Ming Tsao', (SELECT instituteId FROM Institute WHERE alias = 'University Health Network'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'Kingston General Hospital'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'Massachusetts General Hospital'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'Mayo Clinic'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'Ontario Institute for Cancer Research'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'OPCS'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'Ottawa Hospital Research Institute'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'Sheba Medical Center'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'St Josephs Healthcare Hamilton'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'St Josephs Health Centre (Toronto)'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'Sunnybrook Health Sciences Centre'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'UHN McGill'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'University Health Network'),1,NOW(),1,NOW()),
  ('Not Specified', (SELECT instituteId FROM Institute WHERE alias = 'University of Nebraska Medical Center'),1,NOW(),1,NOW()),
  ('Pathology', (SELECT instituteId FROM Institute WHERE alias = 'Ontario Institute for Cancer Research'),1,NOW(),1,NOW()),
  ('Steve Gallinger', (SELECT instituteId FROM Institute WHERE alias = 'Sunnybrook Health Sciences Centre'),1,NOW(),1,NOW()),
  ('Steve Gallinger', (SELECT instituteId FROM Institute WHERE alias = 'University Health Network'),1,NOW(),1,NOW());

INSERT INTO SampleClass (alias, sampleCategory, createdBy, creationDate, updatedBy, lastUpdated, suffix) VALUES
  ('Identity','Identity',1,NOW(),1,NOW(),NULL),
  ('Primary Tumor Tissue','Tissue',1,NOW(),1,NOW(),NULL),
  ('Metastatic Tumor Tissue','Tissue',1,NOW(),1,NOW(),NULL),
  ('Reference Tissue','Tissue',1,NOW(),1,NOW(),NULL),
  ('Xenograft Tissue','Tissue',1,NOW(),1,NOW(),NULL),
  ('Cell Line','Tissue',1,NOW(),1,NOW(),NULL),
  ('CV Slide','Tissue Processing',1,NOW(),1,NOW(),'CV'),
  ('Curls','Tissue Processing',1,NOW(),1,NOW(),'C'),
  ('H E Slide','Tissue Processing',1,NOW(),1,NOW(),'HE'),
  ('LCM Tube','Tissue Processing',1,NOW(),1,NOW(),'LCM'),
  ('gDNA (stock)','Stock',1,NOW(),1,NOW(),'D_S'),
  ('gDNA_wga (stock)','Stock',1,NOW(),1,NOW(),'D_S'),
  ('whole RNA (stock)','Stock',1,NOW(),1,NOW(),'R_S'),
  ('cDNA (stock)','Stock',1,NOW(),1,NOW(),'D_S'),
  ('gDNA (aliquot)','Aliquot',1,NOW(),1,NOW(),'D_'),
  ('gDNA_wga (aliquot)','Aliquot',1,NOW(),1,NOW(),'D_'),
  ('whole RNA (aliquot)','Aliquot',1,NOW(),1,NOW(),'R_'),
  ('smRNA','Aliquot',1,NOW(),1,NOW(),'SM'),
  ('mRNA','Aliquot',1,NOW(),1,NOW(),'MR'),
  ('rRNA_depleted','Aliquot',1,NOW(),1,NOW(),'WT'),
  ('cDNA (aliquot)','Aliquot',1,NOW(),1,NOW(),'D_');

INSERT INTO SampleValidRelationship (parentId, childId, createdBy, creationDate, updatedBy, lastUpdated) VALUES 
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Identity'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'Primary Tumor Tissue'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Identity'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'Metastatic Tumor Tissue'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Identity'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'Reference Tissue'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Identity'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'Xenograft Tissue'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Identity'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'Cell Line'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Primary Tumor Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'CV Slide'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Primary Tumor Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'Curls'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Primary Tumor Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'H E Slide'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Metastatic Tumor Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'CV Slide'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Metastatic Tumor Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'Curls'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Metastatic Tumor Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'H E Slide'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Reference Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'CV Slide'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Reference Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'Curls'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Reference Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'H E Slide'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Xenograft Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'CV Slide'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Xenograft Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'Curls'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Xenograft Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'H E Slide'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'CV Slide'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'LCM Tube'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Curls'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'LCM Tube'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'LCM Tube'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA_wga (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (aliquot)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA_wga (stock)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA_wga (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA_wga (stock)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA_wga (aliquot)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (stock)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (stock)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'cDNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (stock)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (aliquot)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'cDNA (stock)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'cDNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'cDNA (stock)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'cDNA (aliquot)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (aliquot)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'smRNA'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (aliquot)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'mRNA'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (aliquot)'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'rRNA_depleted'),1,NOW(),1,NOW());

INSERT INTO ReferenceGenome (alias) VALUES 
  ('Human hg19 random'),
  ('Human hg19'),
  ('Human hg18 random'),
  ('Human hg18'),
  ('Mouse mm9'),
  ('Rat rn4'),
  ('E. coli DH10B'),
  ('phiX174'),
  ('C. elegans ce6'),
  ('C. pygerythrus'),
  ('Vaccinia JX-594 (OICR)'),
  ('P. falciparum'),
  ('R. sphaeroides'),
  ('S. aureus'),
  ('de novo assembly'),
  ('See comments');
--EndNoTest

-- oicr_sequencers
--StartNoTest
INSERT INTO SequencerReference (referenceId, name, ipAddress, platformId, available, serialNUmber, dateCommissioned, dateDecommissioned, upgradedSequencerReferenceId) VALUES 
(1, 'D00331', UNHEX('7F000001'), 16, 1, 'HSQ-D00331', '2014-01-03', NULL, NULL),
(2, 'D00343', UNHEX('7F000001'), 16, 1, 'D00343', '2014-01-15', NULL, NULL),
(3, 'D00353', UNHEX('7F000001'), 16, 1, NULL, '2013-12-17', NULL, NULL),
(4, 'D00355', UNHEX('7F000001'), 16, 1, NULL, '2014-01-15', NULL, NULL),
(5, 'SN1068', UNHEX('7F000001'), 16, 1, 'HSQ-7001068', '2012-02-03', NULL, NULL),
(6, 'SN1080', UNHEX('7F000001'), 16, 1, 'HSQ-7001080', '2011-10-18', NULL, NULL),
(7, 'SN7001179', UNHEX('7F000001'), 16, 1, 'HSQ-7001179', '2012-02-22', NULL, NULL),
(8, 'SN7001205', UNHEX('7F000001'), 16, 1, 'HSQ-7001205', '2015-10-30', NULL, NULL),
(9, 'SN203', UNHEX('7F000001'), 16, 1, 'HSQ-700203N', '2010-07-23', NULL, NULL),
(10, 'h203', UNHEX('7F000001'), 16, 1, 'HSQ-700203N', '2010-07-23', '2010-10-22', 9),
(11, 'SN231', UNHEX('7F000001'), 16, 1, NULL, '2010-07-23', '2010-10-04', NULL),
(12, 'h239', UNHEX('7F000001'), 16, 1, NULL, '2010-07-23', NULL, NULL),
(13, 'SN393', UNHEX('7F000001'), 16, 1, NULL, '2010-10-19', '2011-11-18', NULL),
(14, 'SN801', UNHEX('7F000001'), 16, 1, 'HSQ-700801', '2011-04-08', NULL, NULL),
(15, 'SN802', UNHEX('7F000001'), 16, 1, 'HSQ-700802', '2011-04-08', NULL, NULL),
(16, 'SN803', UNHEX('7F000001'), 16, 1, 'HSQ-700803', '2011-04-08', '2011-10-28', NULL),
(17, 'SN804', UNHEX('7F000001'), 16, 1, 'HSQ-700804', '2011-04-08', NULL, NULL),
(18, 'M00146', UNHEX('7F000001'), 24, 1, 'MSQ-M146', '2011-10-04', NULL, NULL),
(19, 'M00753', UNHEX('7F000001'), 24, 1, NULL, '2012-05-30', NULL, NULL);
--EndNoTest

-- update_seqs_and_params
--StartNoTest
UPDATE SequencerReference SET platformId = 26 WHERE platformId = 16;

UPDATE SequencingParameters SET platformId = 26 WHERE platformId IN (16, 25);
UPDATE SequencingParameters SET name = 'v3 2×300', paired = 1 WHERE name = '300×200';
--EndNoTest

-- delete_ls454_and_solid
--StartNoTest
DELETE FROM KitDescriptor WHERE platformType IN ('LS454','Solid');
DELETE FROM TagBarcodes WHERE tagFamilyId IN (SELECT tagFamilyId FROM TagBarcodeFamily WHERE platformType = 'LS454');
DELETE FROM TagBarcodeFamily WHERE platformType = 'LS454';
--EndNoTest

-- library_design
--StartNoTest
INSERT INTO LibraryDesign(name, sampleClassId, libraryType, librarySelectionType, libraryStrategyType, suffix) VALUES
  ('WG', (SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (aliquot)'),  (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Paired End'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'PCR'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'WGS'), '_WG'),
 ('TS (Hybrid Selection)', (SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (aliquot)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Paired End'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'Hybrid Selection'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'AMPLICON'), '_TS'),
 ('TS (PCR)', (SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (aliquot)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Paired End'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'PCR'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'AMPLICON'), '_TS'),
 ('EX', (SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (aliquot)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Paired End'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'Hybrid Selection'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'WXS'), '_EX'),
 ('SM', (SELECT sampleClassId FROM SampleClass WHERE alias = 'cDNA (aliquot)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Small RNA'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'size fractionation'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'RNA-Seq'), '_SM'),
 ('WT', (SELECT sampleClassId FROM SampleClass WHERE alias = 'cDNA (aliquot)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Whole Transcriptome'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'cDNA'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'RNA-Seq'), '_WT'),
 ('MR', (SELECT sampleClassId FROM SampleClass WHERE alias = 'cDNA (aliquot)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'mRNA Seq'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'cDNA'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'RNA-Seq'), '_WT'),
 ('CH', (SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (aliquot)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Single End'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'ChIP'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'ChIP-Seq'), '_CH');
--EndNoTest

-- add_cbots
--StartNoTest
INSERT INTO Platform (name, instrumentModel, description, numContainers) VALUES ('Illumina', 'cBot 2', 'Cluster generation system', 1);
INSERT INTO SequencerReference (name, ipAddress, platformId, available) VALUES 
  ('cBot 3', UNHEX('7F000001'), (SELECT platformId FROM Platform WHERE instrumentModel = 'cBot 2'), 1),
  ('cBot 4', UNHEX('7F000001'), (SELECT platformId FROM Platform WHERE instrumentModel = 'cBot 2'), 1),
  ('cBot 5', UNHEX('7F000001'), (SELECT platformId FROM Platform WHERE instrumentModel = 'cBot 2'), 1),
  ('cBot 6', UNHEX('7F000001'), (SELECT platformId FROM Platform WHERE instrumentModel = 'cBot 2'), 1);
--EndNoTest

-- add_more_SVRs
--StartNoTest
INSERT INTO SampleValidRelationship (parentId, childId, createdBy, creationDate, updatedBy, lastUpdated) VALUES 
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Primary Tumor Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Primary Tumor Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Metastatic Tumor Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Metastatic Tumor Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Reference Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Reference Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Xenograft Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Xenograft Tissue'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Cell Line'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'gDNA (stock)'),1,NOW(),1,NOW()),
  ((SELECT sampleClassId FROM SampleClass WHERE alias = 'Cell Line'),(SELECT sampleClassId FROM SampleClass WHERE alias = 'whole RNA (stock)'),1,NOW(),1,NOW());
--EndNoTest

-- refgen_comments
--StartNoTest
UPDATE ReferenceGenome SET alias = 'Special – Look in description' WHERE alias = 'See comments';
--EndNoTest

-- targeted_resequencing
--StartNoTest
insert into TargetedResequencing (alias, description, kitDescriptorId, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('BART_IAD40521_23', 'Used by the BART and BFS projects',(select kitDescriptorId from KitDescriptor where name = 'Ampliseq-Illumina V1'),1,NOW(),1,NOW()),
  ('DYS_IAD78789_185', 'Used by the DYS project',(select kitDescriptorId from KitDescriptor where name = 'AmpliSeq-KAPA Hyper Prep V1'),1,NOW(),1,NOW()),
  ('GECCO_IAD82491', 'Used by the GECCO project',(select kitDescriptorId from KitDescriptor where name = 'AmpliSeq-KAPA Hyper Prep V1'),1,NOW(),1,NOW());
--EndNoTest

-- box_size_use
--StartNoTest
INSERT INTO BoxSize (rows, columns, scannable) VALUES (9, 9, false);

INSERT INTO BoxUse (`alias`)  VALUES ('Storage');
INSERT INTO BoxUse (`alias`)  VALUES ('Libraries');

UPDATE Box
SET boxUseId = (SELECT boxUseId from BoxUse where BoxUse.`alias` = 'Libraries')
WHERE Box.`boxUseId` = (SELECT boxUseId from BoxUse where BoxUse.`alias` = 'Plate');

DELETE FROM BoxUse WHERE BoxUse.alias = 'Plate';
--EndNoTest

-- sequencer_update
--StartNoTest
DELETE FROM SequencingParameters WHERE SequencingParameters.name = 'v4 1×136';

INSERT INTO Platform (name, instrumentModel, description, numContainers)
VALUES ('Illumina', 'NextSeq 550', '4-channel flowgram', 1);

INSERT INTO `SequencingParameters` (`platformId`, `name`, `createdBy`, `updatedBy`, `creationDate`, `lastUpdated`, `readLength`, `paired`, `xpath`)
VALUES
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'NextSeq 550'),'2×151', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 151, TRUE, '//PlannedRead1Cycles = 151 and //PlannedRead2Cycles = 151'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'NextSeq 550'),'2×75', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 75, TRUE, '//PlannedRead1Cycles = 75 and //PlannedRead2Cycles = 75'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'NextSeq 550'),'1×151', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 151, FALSE, '//PlannedRead1Cycles = 151 and not //PlannedRead2Cycles'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'NextSeq 550'),'1×75', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 75, FALSE, '//PlannedRead1Cycles = 75 and not //PlannedRead2Cycles'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'Illumina HiSeq 2500'),'2×251', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 251, TRUE, 'starts-with(//Flowcell, "HiSeq Rapid Flow Cell") and count(//Read[@NumCycles=251]) = 2'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'Illumina MiSeq'),'1×51', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 51, FALSE, 'count(//RunInfoRead[@NumCycles=51]) = 1'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'Illumina MiSeq'),'1×36', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 36, FALSE, 'count(//RunInfoRead[@NumCycles=36]) = 1'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'Illumina MiSeq'),'1×151', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 151, FALSE, 'count(//RunInfoRead[@NumCycles=151]) = 1'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'Illumina MiSeq'),'2x25', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 25, TRUE, 'count(//RunInfoRead[@NumCycles=25]) = 2'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'Illumina MiSeq'),'2x251', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 251, TRUE, 'count(//RunInfoRead[@NumCycles=251]) = 2'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'Illumina MiSeq'),'2x76', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 76, TRUE, 'count(//RunInfoRead[@NumCycles=76]) = 2'),
    ((SELECT platformId from Platform where Platform.`instrumentModel` = 'Illumina MiSeq'),'2x301', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 301, TRUE, 'count(//RunInfoRead[@NumCycles=301]) = 2');

DELETE FROM SequencerReference WHERE SequencerReference.name = 'p00118';

INSERT INTO SequencerReference (name, ipAddress, platformId, available, serialNUmber, dateCommissioned, dateDecommissioned, upgradedSequencerReferenceId)
VALUES 
    ('NB551051', UNHEX('7F000001'), (SELECT platformId from Platform where Platform.`instrumentModel` = 'NextSeq 550'), 1, 'NB551051', '2016-04-26', NULL, NULL),
    ('00118', UNHEX('7F000001'), (SELECT platformId from Platform where Platform.`instrumentModel` = 'PacBio RS'), 1, '00118', '2010-08-16', NULL, NULL);
--EndNoTest

-- add_barcodes
--StartNoTest
INSERT INTO TagBarcodeFamily(name, platformType) VALUES
  ('454', 'LS454'),
  ('iDES 8bp', 'ILLUMINA');

INSERT INTO TagBarcodes(name, sequence, position, tagFamilyId) VALUES
  ('Index 01', 'ATCACG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = '454')),
  ('Index 02', 'CGATGT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = '454')),
  ('Index 03', 'TTAGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = '454')),
  ('Index 04', 'TGACCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = '454')),
  ('Index 05', 'ACAGTG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = '454')),
  ('Index 06', 'GCCAAT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = '454')),
  ('Index 07', 'CAGATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = '454')),
  ('Index 08', 'ACTTGA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = '454')),
  ('Index 09', 'GATCAG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = '454')),
  ('Index 10', 'TAGCTT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = '454')),

  ('Index 01', 'ACGTCACA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'iDES 8bp')),
  ('Index 02', 'CTAAGTGG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'iDES 8bp')),
  ('Index 03', 'TGTAACCG', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'iDES 8bp')),
  ('Index 04', 'TGACCATC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'iDES 8bp')),
  ('Index 05', 'AACTTGGC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'iDES 8bp')),
  ('Index 06', 'TCTCGGTT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'iDES 8bp')),
  ('Index 07', 'GTATGGAC', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'iDES 8bp')),
  ('Index 08', 'TTCTGCCA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'iDES 8bp')),
  ('Index 09', 'CCAACGAA', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'iDES 8bp')),
  ('Index 10', 'ACCACCTT', 1, (SELECT tagFamilyId FROM TagBarcodeFamily WHERE name = 'iDES 8bp'));
--EndNoTest
