INSERT INTO `ReferenceGenome` (`alias`) VALUES
('Human hg19 random'),
('Human hg19'),
('Human hg18 random'),
('Human hg18'),
('Mouse mm9'),
('Rat rn4'),
('E. coli DH10B'),
('phiX174'),
('C. elegans ce6'),
('C. pygerythrus'),
('Vaccinia JX-594 (OICR)'),
('P. falciparum'),
('R. sphaeroides'),
('S. aureus'),
('de novo assemby'),
('See comments');