-- Standard values for an OICR MISO instance

INSERT INTO BoxSize (`rows`, `columns`, scannable) VALUES
  (8,12,true),
  (10,10,false);

INSERT INTO BoxUse (alias) VALUES
  ('DNA'),
  ('RNA'),
  ('Tissue'),
  ('Sequencing'),
  ('Plate');

DELETE FROM `LibraryDesignType`;
INSERT INTO LibraryDesignType (name, description) VALUES
  ('WG', 'Whole genome'),
  ('EX', 'Exome'),
  ('TS', 'Targeted sequencing'),
  ('TR', 'Total RNA library (no selection)'),
  ('WT', 'Whole transcriptome'),
  ('SM', 'smRNA'),
  ('MR', 'mRNA'),
  ('CH', 'ChIP'),
  ('BS', 'Bisulphite');

INSERT INTO `LibraryType` (description, platformType) VALUES
  ('cDNA', 'PacBio'),
  ('Amplicon', 'PacBio'),
  ('2kb Shotgun', 'PacBio'),
  ('10kb Shotgun', 'PacBio'),
  ('20kb Shotgun', 'PacBio'),
  ('Plasmid', 'PacBio'),
  ('BAC', 'PacBio');

INSERT INTO `Platform` (name, instrumentModel, description, numContainers) VALUES
  ('Illumina', 'Illumina HiSeq 2500', '4-channel flowgram', 1),
  ('Illumina', 'Illumina NextSeq 500', '4-channel flowgram', 1),
  ('Illumina', 'Illumina HiSeq X Ten', '4-channel flowgram', 1),
  ('OxfordNanopore', 'MinION', 'Nanopore', 1),
  ('OxfordNanopore', 'GridION', 'Nanopore', 1),
  ('IonTorrent', 'Ion Torrent PGM', 'Ion Torrent', 1),
  ('IonTorrent', 'Ion Torrent Proton', 'Ion Torrent', 1);

INSERT INTO KitDescriptor
  (name, version, manufacturer, partNumber, stockLevel, kitType, platformType, description) VALUES
  ('V4 PE Cluster Kit', 1, 'Illumina', 'PE-401-4001', 4, 'Sequencing', 'Illumina', '(Box 1 of 2): 4 & (Box 2 of 2): 4 & (V4 Flowcells): 4'),
  ('MiSeq Reagent Kit 300 Cycle', 1, 'Illumina', 'MS-102-2002', 4, 'Sequencing', 'Illumina', '(Box 1 of 2): 4 & (Box 2 of 2): 7'),
  ('SBS Reagent Kit 250 Cycle', 1, 'Illumina', 'FC-401-4003', 4, 'Sequencing', 'Illumina', '(Box 1 of 2): 4 & (Box 2 of 2): 4'),
  ('Rapid V2 PE Cluster Kit', 1, 'Illumina', 'PE-402-4002', 2, 'Clustering', 'Illumina', '(Cluster Kits): 2 & (Rapid V2 Flowcells): 2'),
  ('Rapid V2 SBS Reagent Kit 200 Cycle', 1, 'Illumina', 'FC-402-4021', 1, 'Sequencing', 'Illumina', '(Box 1 of 2): 1 & (Box 2 of 2): 1'),
  ('Rapid V2 SBS Reagent Kit 50 Cycle', 1, 'Illumina', 'FC-402-4022', 2, 'Sequencing', 'Illumina', '(Box 1 of 2): 2 & (Box 2 of 2): 2'),
  ('HiSeq Rapid Duo cBot Sample Plate Box', 1, 'Illumina', 'n/a', 2, 'Clustering', 'Illumina', 'n/a'),
  ('TruSeq RapidRun Duo cBot', 1, 'Illumina', 'CT-402-4001', 1, 'Clustering', 'Illumina', 'Expired'),
  ('SR Rapid Cluster Kit', 1, 'Illumina', 'GD-401-3001', 1, 'Clustering', 'Illumina', 'Expired (Cluster Kit): 1 & (SR Rapid Flowcells): 1'),
  ('Rapid PE Cluster Kit', 1, 'Illumina', 'GD-402-4001', 4, 'Clustering', 'Illumina', 'Expired. (Cluster Kit): 4 & (Rapid Flowcells): 6'),
  ('V3 PE Cluster Kit', 1, 'Illumina', 'PE-401-3001', 7, 'Clustering', 'Illumina', '(Box 1 of 2): 10 & (Box 2 of 2): 7 & (V3 Flowcells): 14 (Truseq Multiplex Seq Primer): 13'),
  ('SBS Rapid Run Kits - 200 Cycle', 1, 'Illumina', 'FC-402-4001', 7, 'Sequencing', 'Illumina', 'Expired'),
  ('SBS Rapid Run Kits - 50 Cycle', 1, 'Illumina', 'FC-402-4002', 1, 'Sequencing', 'Illumina', 'Expired'),
  ('SBS Reagent Kit 200 Cycle', 1, 'Illumina', 'FC-401-3001', 5, 'Sequencing', 'Illumina', '(Box 1 of 2): 9 & (Box 2 of 2): 5. Box 1 - 5 expired. Box 2 - 2 expired'),
  ('Rapid V2 SBS Reagent Kit 500 cycle', 1, 'Illumina', 'FC-402-4023', 1, 'Sequencing', 'Illumina', '(Box 1 of 2): 1 & (Box 2 of 2): 1'),
  ('Rapid Duo cBot Sample Plate Box', 1, 'Illumina', 'n/a', 2, 'Clustering', 'Illumina', 'n/a'),
  ('MiSeq Reagent Kit 50 Cycle', 1, 'Illumina', 'MS-102-2001', 0, 'Sequencing', 'Illumina', '(Box 1 of 2): 0 & (Box 2 of 2): 9'),
  ('MiSeq Reagent Kit 500 cycle', 1, 'Illumina', 'MS-102-2003', 1, 'Sequencing', 'Illumina', '(Box 1 of 2): 1--Expired & (Box 2 of 2): 11'),
  ('Dual Index Seq. Primer Paired End', 1, 'Illumina', 'PE-121-1003', 14, 'Sequencing', 'Illumina', 'n/a'),
  ('Dual Index Seq. Primer Single End', 1, 'Illumina', 'FC-121-1003', 2, 'Sequencing', 'Illumina', 'All Expired'),
  ('MiSeq Reagent Kit 600 Cycle (V3)', 1, 'Illumina', 'MS-102-3003', 1, 'Sequencing', 'Illumina', '(Box 1 of 2): 1--Expired & (Box 2 of 2): 1'),
  ('SR Cluster Kit', 1, 'Illumina', 'GD-401-4001', 1, 'Sequencing', 'Illumina', '(Cluster Kit): 1-Expired & (SR Flowcells): 2'),
  ('HiSeq Rehyb V4', 1, 'Illumina', 'GD-403-4001', 4, 'Sequencing', 'Illumina', '4 Expired'),
  ('Multiprimer Re-hybridization Plate', 1, 'Illumina', 'GD-305-1001', 3, 'Sequencing', 'Illumina', '3 Expired'),
  ('Agilent SureSelect XT', '0', 'Agilent', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('Agilent SureSelect XT2', '0', 'Agilent', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('AmpliSeq-Illumina Exome V1', '1', 'AmpliSeq', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('AmpliSeq-Illumina V1', '1', 'AmpliSeq', '1', '0', 'Library', 'Illumina', 'AmpliSeq-Illumina Modified Protocol Version 1'),
  ('AmpliSeq-KAPA Hyper Prep V1', '1', 'AmpliSeq', '1', '0', 'Library', 'Illumina', 'Testing'),
  ('GA_PE', '0', 'GA', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('GA_TruSeq_SmRNA', '0', 'GA', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('KAPA BC OnBead', '0', 'KAPA', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('KAPA Hyper Prep', '0', 'KAPA', '1', '0', 'Library', 'Illumina', 'KK8504 With KAPA Library Amplification Primer Mix (10X 96 reactions)'),
  ('Nextera DNA', '0', 'Nextera', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('Thunderbolt Cancer Panel', '0', 'Thunderbolt', '1', '0', 'Library', 'Illumina', 'n/a'),
  ('TruSeq Amplicon - Cancer Panel', '0', 'TruSeq', '1', '0', 'Library', 'Illumina', 'Associated with Illumina PE libraries. Not compatible with the HiSeq - only MiSeq'),
  ('TruSeq RNA Access', '0', 'TruSeq', 'RS-301-2001', '0', 'Library', 'Illumina', 'RS-301-2001'),
  ('TruSeq_Stranded_mRNA', '0', 'TruSeq', '1', '0', 'Library', 'Illumina', 'Illumina Directional mRNA Library'),
  ('TruSeq_Stranded_TotalRNA', '0', 'TruSeq', '1', '0', 'Library', 'Illumina', 'Illumina Directional Whole Transcriptome Library');

DELETE FROM TagBarcodes WHERE strategyName = 'SureSelect XT2';
INSERT INTO TagBarcodes (name, sequence, platformName, strategyName) VALUES
  ('01', 'AACGTGAT', 'Illumina', 'NEXTflex 8bp'),
  ('02', 'AAACATCG', 'Illumina', 'NEXTflex 8bp'),
  ('03', 'ATGCCTAA', 'Illumina', 'NEXTflex 8bp'),
  ('04', 'AGTGGTCA', 'Illumina', 'NEXTflex 8bp'),
  ('05', 'ACCACTGT', 'Illumina', 'NEXTflex 8bp'),
  ('06', 'ACATTGGC', 'Illumina', 'NEXTflex 8bp'),
  ('07', 'CAGATCTG', 'Illumina', 'NEXTflex 8bp'),
  ('08', 'CATCAAGT', 'Illumina', 'NEXTflex 8bp'),
  ('09', 'CGCTGATC', 'Illumina', 'NEXTflex 8bp'),
  ('10', 'ACAAGCTA', 'Illumina', 'NEXTflex 8bp'),
  ('11', 'CTGTAGCC', 'Illumina', 'NEXTflex 8bp'),
  ('12', 'AGTACAAG', 'Illumina', 'NEXTflex 8bp'),
  ('13', 'AACAACCA', 'Illumina', 'NEXTflex 8bp'),
  ('14', 'AACCGAGA', 'Illumina', 'NEXTflex 8bp'),
  ('15', 'AACGCTTA', 'Illumina', 'NEXTflex 8bp'),
  ('16', 'AAGACGGA', 'Illumina', 'NEXTflex 8bp'),
  ('17', 'AAGGTACA', 'Illumina', 'NEXTflex 8bp'),
  ('18', 'ACACAGAA', 'Illumina', 'NEXTflex 8bp'),
  ('19', 'ACAGCAGA', 'Illumina', 'NEXTflex 8bp'),
  ('20', 'ACCTCCAA', 'Illumina', 'NEXTflex 8bp'),
  ('21', 'ACGCTCGA', 'Illumina', 'NEXTflex 8bp'),
  ('22', 'ACGTATCA', 'Illumina', 'NEXTflex 8bp'),
  ('23', 'ACTATGCA', 'Illumina', 'NEXTflex 8bp'),
  ('24', 'AGAGTCAA', 'Illumina', 'NEXTflex 8bp'),
  ('25', 'AGATCGCA', 'Illumina', 'NEXTflex 8bp'),
  ('26', 'AGCAGGAA', 'Illumina', 'NEXTflex 8bp'),
  ('27', 'AGTCACTA', 'Illumina', 'NEXTflex 8bp'),
  ('28', 'ATCCTGTA', 'Illumina', 'NEXTflex 8bp'),
  ('29', 'ATTGAGGA', 'Illumina', 'NEXTflex 8bp'),
  ('30', 'CAACCACA', 'Illumina', 'NEXTflex 8bp'),
  ('31', 'GACTAGTA', 'Illumina', 'NEXTflex 8bp'),
  ('32', 'CAATGGAA', 'Illumina', 'NEXTflex 8bp'),
  ('33', 'CACTTCGA', 'Illumina', 'NEXTflex 8bp'),
  ('34', 'CAGCGTTA', 'Illumina', 'NEXTflex 8bp'),
  ('35', 'CATACCAA', 'Illumina', 'NEXTflex 8bp'),
  ('36', 'CCAGTTCA', 'Illumina', 'NEXTflex 8bp'),
  ('37', 'CCGAAGTA', 'Illumina', 'NEXTflex 8bp'),
  ('38', 'CCGTGAGA', 'Illumina', 'NEXTflex 8bp'),
  ('39', 'CCTCCTGA', 'Illumina', 'NEXTflex 8bp'),
  ('40', 'CGAACTTA', 'Illumina', 'NEXTflex 8bp'),
  ('41', 'CGACTGGA', 'Illumina', 'NEXTflex 8bp'),
  ('42', 'CGCATACA', 'Illumina', 'NEXTflex 8bp'),
  ('43', 'CTCAATGA', 'Illumina', 'NEXTflex 8bp'),
  ('44', 'CTGAGCCA', 'Illumina', 'NEXTflex 8bp'),
  ('45', 'CTGGCATA', 'Illumina', 'NEXTflex 8bp'),
  ('46', 'GAATCTGA', 'Illumina', 'NEXTflex 8bp'),
  ('47', 'CAAGACTA', 'Illumina', 'NEXTflex 8bp'),
  ('48', 'GAGCTGAA', 'Illumina', 'NEXTflex 8bp'),
  ('49', 'GATAGACA', 'Illumina', 'NEXTflex 8bp'),
  ('50', 'GCCACATA', 'Illumina', 'NEXTflex 8bp'),
  ('51', 'GCGAGTAA', 'Illumina', 'NEXTflex 8bp'),
  ('52', 'GCTAACGA', 'Illumina', 'NEXTflex 8bp'),
  ('53', 'GCTCGGTA', 'Illumina', 'NEXTflex 8bp'),
  ('54', 'GGAGAACA', 'Illumina', 'NEXTflex 8bp'),
  ('55', 'GGTGCGAA', 'Illumina', 'NEXTflex 8bp'),
  ('56', 'GTACGCAA', 'Illumina', 'NEXTflex 8bp'),
  ('57', 'GTCGTAGA', 'Illumina', 'NEXTflex 8bp'),
  ('58', 'GTCTGTCA', 'Illumina', 'NEXTflex 8bp'),
  ('59', 'GTGTTCTA', 'Illumina', 'NEXTflex 8bp'),
  ('60', 'TAGGATGA', 'Illumina', 'NEXTflex 8bp'),
  ('61', 'TATCAGCA', 'Illumina', 'NEXTflex 8bp'),
  ('62', 'TCCGTCTA', 'Illumina', 'NEXTflex 8bp'),
  ('63', 'TCTTCACA', 'Illumina', 'NEXTflex 8bp'),
  ('64', 'TGAAGAGA', 'Illumina', 'NEXTflex 8bp'),
  ('65', 'TGGAACAA', 'Illumina', 'NEXTflex 8bp'),
  ('66', 'TGGCTTCA', 'Illumina', 'NEXTflex 8bp'),
  ('67', 'TGGTGGTA', 'Illumina', 'NEXTflex 8bp'),
  ('68', 'TTCACGCA', 'Illumina', 'NEXTflex 8bp'),
  ('69', 'AACTCACC', 'Illumina', 'NEXTflex 8bp'),
  ('70', 'AAGAGATC', 'Illumina', 'NEXTflex 8bp'),
  ('71', 'AAGGACAC', 'Illumina', 'NEXTflex 8bp'),
  ('72', 'AATCCGTC', 'Illumina', 'NEXTflex 8bp'),
  ('73', 'AATGTTGC', 'Illumina', 'NEXTflex 8bp'),
  ('74', 'ACACGACC', 'Illumina', 'NEXTflex 8bp'),
  ('75', 'ACAGATTC', 'Illumina', 'NEXTflex 8bp'),
  ('76', 'AGATGTAC', 'Illumina', 'NEXTflex 8bp'),
  ('77', 'AGCACCTC', 'Illumina', 'NEXTflex 8bp'),
  ('78', 'AGCCATGC', 'Illumina', 'NEXTflex 8bp'),
  ('79', 'AGGCTAAC', 'Illumina', 'NEXTflex 8bp'),
  ('80', 'ATAGCGAC', 'Illumina', 'NEXTflex 8bp'),
  ('81', 'ATCATTCC', 'Illumina', 'NEXTflex 8bp'),
  ('82', 'ATTGGCTC', 'Illumina', 'NEXTflex 8bp'),
  ('83', 'CAAGGAGC', 'Illumina', 'NEXTflex 8bp'),
  ('84', 'CACCTTAC', 'Illumina', 'NEXTflex 8bp'),
  ('85', 'CCATCCTC', 'Illumina', 'NEXTflex 8bp'),
  ('86', 'CCGACAAC', 'Illumina', 'NEXTflex 8bp'),
  ('87', 'CCTAATCC', 'Illumina', 'NEXTflex 8bp'),
  ('88', 'CCTCTATC', 'Illumina', 'NEXTflex 8bp'),
  ('89', 'CGACACAC', 'Illumina', 'NEXTflex 8bp'),
  ('90', 'CGGATTGC', 'Illumina', 'NEXTflex 8bp'),
  ('91', 'CTAAGGTC', 'Illumina', 'NEXTflex 8bp'),
  ('92', 'GAACAGGC', 'Illumina', 'NEXTflex 8bp'),
  ('93', 'GACAGTGC', 'Illumina', 'NEXTflex 8bp'),
  ('94', 'GAGTTAGC', 'Illumina', 'NEXTflex 8bp'),
  ('95', 'GATGAATC', 'Illumina', 'NEXTflex 8bp'),
  ('96', 'GCCAAGAC', 'Illumina', 'NEXTflex 8bp'),
  ('S501', 'TAGATCGC', 'Illumina', 'Nextera'),
  ('S502', 'CTCTCTAT', 'Illumina', 'Nextera'),
  ('S503', 'TATCCTCT', 'Illumina', 'Nextera'),
  ('S504', 'AGAGTAGA', 'Illumina', 'Nextera'),
  ('S505', 'GTAAGGAG', 'Illumina', 'Nextera'),
  ('S506', 'ACTGCATA', 'Illumina', 'Nextera'),
  ('S507', 'AAGGAGTA', 'Illumina', 'Nextera'),
  ('S508', 'CTAAGCCT', 'Illumina', 'Nextera'),
  ('N701', 'TAAGGCGA', 'Illumina', 'Nextera'),
  ('N702', 'CGTACTAG', 'Illumina', 'Nextera'),
  ('N703', 'AGGCAGAA', 'Illumina', 'Nextera'),
  ('N704', 'TCCTGAGC', 'Illumina', 'Nextera'),
  ('N705', 'GGACTCCT', 'Illumina', 'Nextera'),
  ('N706', 'TAGGCATG', 'Illumina', 'Nextera'),
  ('N707', 'CTCTCTAC', 'Illumina', 'Nextera'),
  ('N708', 'CAGAGAGG', 'Illumina', 'Nextera'),
  ('N709', 'GCTACGCT', 'Illumina', 'Nextera'),
  ('N710', 'CGAGGCTG', 'Illumina', 'Nextera'),
  ('N711', 'AAGAGGCA', 'Illumina', 'Nextera'),
  ('N712', 'GTAGAGGA', 'Illumina', 'Nextera'),
  ('BC1', 'ATCCGTAC', 'Illumina', 'RBC1'),
  ('BC2', 'GTTCACAG', 'Illumina', 'RBC1'),
  ('BC3', 'TGCTACGA', 'Illumina', 'RBC1'),
  ('BC4', 'AGACTCAC', 'Illumina', 'RBC1'),
  ('BC5', 'ATCCAAGC', 'Illumina', 'RBC1'),
  ('BC6', 'CGCATTCA', 'Illumina', 'RBC1'),
  ('BC7', 'ATGACACG', 'Illumina', 'RBC1'),
  ('BC8', 'AACTACGG', 'Illumina', 'RBC1'),
  ('BC9', 'GAGGCTTA', 'Illumina', 'RBC1'),
  ('BC10', 'GACTTCGT', 'Illumina', 'RBC1'),
  ('BC11', 'GTCGTTGT', 'Illumina', 'RBC1'),
  ('BC12', 'TCTGCTTC', 'Illumina', 'RBC1'),
  ('BC13', 'GAGGACTT', 'Illumina', 'RBC1'),
  ('BC14', 'TCCTCGAT', 'Illumina', 'RBC1'),
  ('BC15', 'AAGCAGGA', 'Illumina', 'RBC1'),
  ('BC16', 'TTCTAGGC', 'Illumina', 'RBC1'),
  ('BC17', 'GCGTAACT', 'Illumina', 'RBC1'),
  ('BC18', 'GTGATCCA', 'Illumina', 'RBC1'),
  ('BC19', 'GTGCAGTT', 'Illumina', 'RBC1'),
  ('BC20', 'GACCGTAA', 'Illumina', 'RBC1'),
  ('BC21', 'TGATCGTC', 'Illumina', 'RBC1'),
  ('BC22', 'GTTCAAGG', 'Illumina', 'RBC1'),
  ('BC23', 'CCATTCGT', 'Illumina', 'RBC1'),
  ('BC24', 'AGTATGCC', 'Illumina', 'RBC1'),
  ('1', 'ATCACG', 'Illumina', 'Illumina 6bp'),
  ('2', 'CGATGT', 'Illumina', 'Illumina 6bp'),
  ('3', 'TTAGGC', 'Illumina', 'Illumina 6bp'),
  ('4', 'TGACCA', 'Illumina', 'Illumina 6bp'),
  ('5', 'ACAGTG', 'Illumina', 'Illumina 6bp'),
  ('6', 'GCCAAT', 'Illumina', 'Illumina 6bp'),
  ('7', 'CAGATC', 'Illumina', 'Illumina 6bp'),
  ('8', 'ACTTGA', 'Illumina', 'Illumina 6bp'),
  ('9', 'GATCAG', 'Illumina', 'Illumina 6bp'),
  ('10', 'TAGCTT', 'Illumina', 'Illumina 6bp'),
  ('11', 'GGCTAC', 'Illumina', 'Illumina 6bp'),
  ('12', 'CTTGTA', 'Illumina', 'Illumina 6bp'),
  ('13', 'AGTCAA', 'Illumina', 'Illumina 6bp'),
  ('14', 'AGTTCC', 'Illumina', 'Illumina 6bp'),
  ('15', 'ATGTCA', 'Illumina', 'Illumina 6bp'),
  ('16', 'CCGTCC', 'Illumina', 'Illumina 6bp'),
  ('17', 'GTAGAG', 'Illumina', 'Illumina 6bp'),
  ('18', 'GTCCGC', 'Illumina', 'Illumina 6bp'),
  ('19', 'GTGAAA', 'Illumina', 'Illumina 6bp'),
  ('20', 'GTGGCC', 'Illumina', 'Illumina 6bp'),
  ('21', 'GTTTCG', 'Illumina', 'Illumina 6bp'),
  ('22', 'CGTACG', 'Illumina', 'Illumina 6bp'),
  ('23', 'GAGTGG', 'Illumina', 'Illumina 6bp'),
  ('24', 'GGTAGC', 'Illumina', 'Illumina 6bp'),
  ('25', 'ACTGAT', 'Illumina', 'Illumina 6bp'),
  ('26', 'ATGAGC', 'Illumina', 'Illumina 6bp'),
  ('27', 'ATTCCT', 'Illumina', 'Illumina 6bp'),
  ('28', 'CAAAAG', 'Illumina', 'Illumina 6bp'),
  ('29', 'CAACTA', 'Illumina', 'Illumina 6bp'),
  ('30', 'CACCGG', 'Illumina', 'Illumina 6bp'),
  ('31', 'CACGAT', 'Illumina', 'Illumina 6bp'),
  ('32', 'CACTCA', 'Illumina', 'Illumina 6bp'),
  ('33', 'CAGGCG', 'Illumina', 'Illumina 6bp'),
  ('34', 'CATGGC', 'Illumina', 'Illumina 6bp'),
  ('35', 'CATTTT', 'Illumina', 'Illumina 6bp'),
  ('36', 'CCAACA', 'Illumina', 'Illumina 6bp'),
  ('37', 'CGGAAT', 'Illumina', 'Illumina 6bp'),
  ('38', 'CTAGCT', 'Illumina', 'Illumina 6bp'),
  ('39', 'CTATAC', 'Illumina', 'Illumina 6bp'),
  ('40', 'CTCAGA', 'Illumina', 'Illumina 6bp'),
  ('41', 'GACGAC', 'Illumina', 'Illumina 6bp'),
  ('42', 'TAATCG', 'Illumina', 'Illumina 6bp'),
  ('43', 'TACAGC', 'Illumina', 'Illumina 6bp'),
  ('44', 'TATAAT', 'Illumina', 'Illumina 6bp'),
  ('45', 'TCATTC', 'Illumina', 'Illumina 6bp'),
  ('46', 'TCCCGA', 'Illumina', 'Illumina 6bp'),
  ('47', 'TCGAAG', 'Illumina', 'Illumina 6bp'),
  ('48', 'TCGGCA', 'Illumina', 'Illumina 6bp'),
  ('None', '', 'Illumina', 'Illumina 6bp'),
  ('1', 'AACGTGAT', 'Illumina', 'Agilent'),
  ('2', 'AAACATCG', 'Illumina', 'Agilent'),
  ('3', 'ATGCCTAA', 'Illumina', 'Agilent'),
  ('4', 'AGTGGTCA', 'Illumina', 'Agilent'),
  ('5', 'ACCACTGT', 'Illumina', 'Agilent'),
  ('6', 'ACATTGGC', 'Illumina', 'Agilent'),
  ('7', 'CAGATCTG', 'Illumina', 'Agilent'),
  ('8', 'CATCAAGT', 'Illumina', 'Agilent'),
  ('9', 'CGCTGATC', 'Illumina', 'Agilent'),
  ('10', 'ACAAGCTA', 'Illumina', 'Agilent'),
  ('11', 'CTGTAGCC', 'Illumina', 'Agilent'),
  ('12', 'AGTACAAG', 'Illumina', 'Agilent'),
  ('13', 'AACAACCA', 'Illumina', 'Agilent'),
  ('14', 'AACCGAGA', 'Illumina', 'Agilent'),
  ('15', 'AACGCTTA', 'Illumina', 'Agilent'),
  ('16', 'AAGACGGA', 'Illumina', 'Agilent'),
  ('17', 'AAGGTACA', 'Illumina', 'Agilent'),
  ('18', 'ACACAGAA', 'Illumina', 'Agilent'),
  ('19', 'ACAGCAGA', 'Illumina', 'Agilent'),
  ('20', 'ACCTCCAA', 'Illumina', 'Agilent'),
  ('21', 'ACGCTCGA', 'Illumina', 'Agilent'),
  ('22', 'ACGTATCA', 'Illumina', 'Agilent'),
  ('23', 'ACTATGCA', 'Illumina', 'Agilent'),
  ('24', 'AGAGTCAA', 'Illumina', 'Agilent'),
  ('25', 'AGATCGCA', 'Illumina', 'Agilent'),
  ('26', 'AGCAGGAA', 'Illumina', 'Agilent'),
  ('27', 'AGTCACTA', 'Illumina', 'Agilent'),
  ('28', 'ATCCTGTA', 'Illumina', 'Agilent'),
  ('29', 'ATTGAGGA', 'Illumina', 'Agilent'),
  ('30', 'CAACCACA', 'Illumina', 'Agilent'),
  ('31', 'CAAGACTA', 'Illumina', 'Agilent'),
  ('32', 'CAATGGAA', 'Illumina', 'Agilent'),
  ('33', 'CACTTCGA', 'Illumina', 'Agilent'),
  ('34', 'CAGCGTTA', 'Illumina', 'Agilent'),
  ('35', 'CATACCAA', 'Illumina', 'Agilent'),
  ('36', 'CCAGTTCA', 'Illumina', 'Agilent'),
  ('37', 'CCGAAGTA', 'Illumina', 'Agilent'),
  ('38', 'CCGTGAGA', 'Illumina', 'Agilent'),
  ('39', 'CCTCCTGA', 'Illumina', 'Agilent'),
  ('40', 'CGAACTTA', 'Illumina', 'Agilent'),
  ('41', 'CGACTGGA', 'Illumina', 'Agilent'),
  ('42', 'CGCATACA', 'Illumina', 'Agilent'),
  ('43', 'CTCAATGA', 'Illumina', 'Agilent'),
  ('44', 'CTGAGCCA', 'Illumina', 'Agilent'),
  ('45', 'CTGGCATA', 'Illumina', 'Agilent'),
  ('46', 'GAATCTGA', 'Illumina', 'Agilent'),
  ('47', 'GACTAGTA', 'Illumina', 'Agilent'),
  ('48', 'GAGCTGAA', 'Illumina', 'Agilent'),
  ('49', 'GATAGACA', 'Illumina', 'Agilent'),
  ('50', 'GCCACATA', 'Illumina', 'Agilent'),
  ('51', 'GCGAGTAA', 'Illumina', 'Agilent'),
  ('52', 'GCTAACGA', 'Illumina', 'Agilent'),
  ('53', 'GCTCGGTA', 'Illumina', 'Agilent'),
  ('54', 'GGAGAACA', 'Illumina', 'Agilent'),
  ('55', 'GGTGCGAA', 'Illumina', 'Agilent'),
  ('56', 'GTACGCAA', 'Illumina', 'Agilent'),
  ('57', 'GTCGTAGA', 'Illumina', 'Agilent'),
  ('58', 'GTCTGTCA', 'Illumina', 'Agilent'),
  ('59', 'GTGTTCTA', 'Illumina', 'Agilent'),
  ('60', 'TAGGATGA', 'Illumina', 'Agilent'),
  ('61', 'TATCAGCA', 'Illumina', 'Agilent'),
  ('62', 'TCCGTCTA', 'Illumina', 'Agilent'),
  ('63', 'TCTTCACA', 'Illumina', 'Agilent'),
  ('64', 'TGAAGAGA', 'Illumina', 'Agilent'),
  ('65', 'TGGAACAA', 'Illumina', 'Agilent'),
  ('66', 'TGGCTTCA', 'Illumina', 'Agilent'),
  ('67', 'TGGTGGTA', 'Illumina', 'Agilent'),
  ('68', 'TTCACGCA', 'Illumina', 'Agilent'),
  ('69', 'AACTCACC', 'Illumina', 'Agilent'),
  ('70', 'AAGAGATC', 'Illumina', 'Agilent'),
  ('71', 'AAGGACAC', 'Illumina', 'Agilent'),
  ('72', 'AATCCGTC', 'Illumina', 'Agilent'),
  ('73', 'AATGTTGC', 'Illumina', 'Agilent'),
  ('74', 'ACACGACC', 'Illumina', 'Agilent'),
  ('75', 'ACAGATTC', 'Illumina', 'Agilent'),
  ('76', 'AGATGTAC', 'Illumina', 'Agilent'),
  ('77', 'AGCACCTC', 'Illumina', 'Agilent'),
  ('78', 'AGCCATGC', 'Illumina', 'Agilent'),
  ('79', 'AGGCTAAC', 'Illumina', 'Agilent'),
  ('80', 'ATAGCGAC', 'Illumina', 'Agilent'),
  ('81', 'ATCATTCC', 'Illumina', 'Agilent'),
  ('82', 'ATTGGCTC', 'Illumina', 'Agilent'),
  ('83', 'CAAGGAGC', 'Illumina', 'Agilent'),
  ('84', 'CACCTTAC', 'Illumina', 'Agilent'),
  ('85', 'CCATCCTC', 'Illumina', 'Agilent'),
  ('86', 'CCGACAAC', 'Illumina', 'Agilent'),
  ('87', 'CCTAATCC', 'Illumina', 'Agilent'),
  ('88', 'CCTCTATC', 'Illumina', 'Agilent'),
  ('89', 'CGACACAC', 'Illumina', 'Agilent'),
  ('90', 'CGGATTGC', 'Illumina', 'Agilent'),
  ('91', 'CTAAGGTC', 'Illumina', 'Agilent'),
  ('92', 'GAACAGGC', 'Illumina', 'Agilent'),
  ('93', 'GACAGTGC', 'Illumina', 'Agilent'),
  ('94', 'GAGTTAGC', 'Illumina', 'Agilent'),
  ('95', 'GATGAATC', 'Illumina', 'Agilent'),
  ('96', 'GCCAAGAC', 'Illumina', 'Agilent'),
  ('BC1', 'ATCACG', 'Illumina', 'TruSeq smRNA'),
  ('BC2', 'CGATGT', 'Illumina', 'TruSeq smRNA'),
  ('BC3', 'TTAGGC', 'Illumina', 'TruSeq smRNA'),
  ('BC4', 'TGACCA', 'Illumina', 'TruSeq smRNA'),
  ('BC5', 'ACAGTG', 'Illumina', 'TruSeq smRNA'),
  ('BC6', 'GCCAAT', 'Illumina', 'TruSeq smRNA'),
  ('BC7', 'CAGATC', 'Illumina', 'TruSeq smRNA'),
  ('BC8', 'ACTTGA', 'Illumina', 'TruSeq smRNA'),
  ('BC9', 'GATCAG', 'Illumina', 'TruSeq smRNA'),
  ('BC10', 'TAGCTT', 'Illumina', 'TruSeq smRNA'),
  ('BC11', 'GGCTAC', 'Illumina', 'TruSeq smRNA'),
  ('BC12', 'CTTGTA', 'Illumina', 'TruSeq smRNA'),
  ('BC13', 'AGTCAA', 'Illumina', 'TruSeq smRNA'),
  ('BC14', 'AGTTCC', 'Illumina', 'TruSeq smRNA'),
  ('BC15', 'ATGTCA', 'Illumina', 'TruSeq smRNA'),
  ('BC16', 'CCGTCC', 'Illumina', 'TruSeq smRNA'),
  ('BC17', 'GTAGAG', 'Illumina', 'TruSeq smRNA'),
  ('BC18', 'GTCCGC', 'Illumina', 'TruSeq smRNA'),
  ('BC19', 'GTGAAA', 'Illumina', 'TruSeq smRNA'),
  ('BC20', 'GTGGCC', 'Illumina', 'TruSeq smRNA'),
  ('BC21', 'GTTTCG', 'Illumina', 'TruSeq smRNA'),
  ('BC22', 'CGTACG', 'Illumina', 'TruSeq smRNA'),
  ('BC23', 'GAGTGG', 'Illumina', 'TruSeq smRNA'),
  ('BC24', 'GGTAGC', 'Illumina', 'TruSeq smRNA'),
  ('01', 'ATCGATCG', 'Illumina', 'TCRindex2'),
  ('02', 'TCGATCGA', 'Illumina', 'TCRindex2'),
  ('03', 'CGATCGAT', 'Illumina', 'TCRindex2'),
  ('04', 'GATCGATC', 'Illumina', 'TCRindex2'),
  ('A01', 'ATGCCTAA', 'Illumina', 'SureSelect XT2'),
  ('A02', 'AGCAGGAA', 'Illumina', 'SureSelect XT2'),
  ('A03', 'ATCATTCC', 'Illumina', 'SureSelect XT2'),
  ('A04', 'AACTCACC', 'Illumina', 'SureSelect XT2'),
  ('A05', 'AACGCTTA', 'Illumina', 'SureSelect XT2'),
  ('A06', 'AGCCATGC', 'Illumina', 'SureSelect XT2'),
  ('A07', 'ACGTATCA', 'Illumina', 'SureSelect XT2'),
  ('A08', 'CAGCGTTA', 'Illumina', 'SureSelect XT2'),
  ('A09', 'CTCAATGA', 'Illumina', 'SureSelect XT2'),
  ('A10', 'AATGTTGC', 'Illumina', 'SureSelect XT2'),
  ('A11', 'CCAGTTCA', 'Illumina', 'SureSelect XT2'),
  ('A12', 'CAAGGAGC', 'Illumina', 'SureSelect XT2'),
  ('B01', 'GAATCTGA', 'Illumina', 'SureSelect XT2'),
  ('B02', 'GAGCTGAA', 'Illumina', 'SureSelect XT2'),
  ('B03', 'GCCACATA', 'Illumina', 'SureSelect XT2'),
  ('B04', 'GCTAACGA', 'Illumina', 'SureSelect XT2'),
  ('B05', 'GGAGAACA', 'Illumina', 'SureSelect XT2'),
  ('B06', 'GTACGCAA', 'Illumina', 'SureSelect XT2'),
  ('B07', 'GTCTGTCA', 'Illumina', 'SureSelect XT2'),
  ('B08', 'TAGGATGA', 'Illumina', 'SureSelect XT2'),
  ('B09', 'TCCGTCTA', 'Illumina', 'SureSelect XT2'),
  ('B10', 'TGAAGAGA', 'Illumina', 'SureSelect XT2'),
  ('B11', 'TGGCTTCA', 'Illumina', 'SureSelect XT2'),
  ('B12', 'TTCACGCA', 'Illumina', 'SureSelect XT2'),
  ('C01', 'AACGTGAT', 'Illumina', 'SureSelect XT2'),
  ('C02', 'AAACATCG', 'Illumina', 'SureSelect XT2'),
  ('C03', 'ACCACTGT', 'Illumina', 'SureSelect XT2'),
  ('C04', 'CAGATCTG', 'Illumina', 'SureSelect XT2'),
  ('C05', 'CATCAAGT', 'Illumina', 'SureSelect XT2'),
  ('C06', 'AGTACAAG', 'Illumina', 'SureSelect XT2'),
  ('C07', 'CTAAGGTC', 'Illumina', 'SureSelect XT2'),
  ('C08', 'AGTGGTCA', 'Illumina', 'SureSelect XT2'),
  ('C09', 'AGGCTAAC', 'Illumina', 'SureSelect XT2'),
  ('C10', 'AGATCGCA', 'Illumina', 'SureSelect XT2'),
  ('C11', 'CGACTGGA', 'Illumina', 'SureSelect XT2'),
  ('C12', 'CACCTTAC', 'Illumina', 'SureSelect XT2'),
  ('D01', 'CACTTCGA', 'Illumina', 'SureSelect XT2'),
  ('D02', 'GAGTTAGC', 'Illumina', 'SureSelect XT2'),
  ('D03', 'CTGGCATA', 'Illumina', 'SureSelect XT2'),
  ('D04', 'ATCCTGTA', 'Illumina', 'SureSelect XT2'),
  ('D05', 'AAGGTACA', 'Illumina', 'SureSelect XT2'),
  ('D06', 'ACATTGGC', 'Illumina', 'SureSelect XT2'),
  ('D07', 'CGACACAC', 'Illumina', 'SureSelect XT2'),
  ('D08', 'ACAGCAGA', 'Illumina', 'SureSelect XT2'),
  ('D09', 'CCATCCTC', 'Illumina', 'SureSelect XT2'),
  ('D10', 'AAGAGATC', 'Illumina', 'SureSelect XT2'),
  ('D11', 'CAAGACTA', 'Illumina', 'SureSelect XT2'),
  ('D12', 'AAGACGGA', 'Illumina', 'SureSelect XT2'),
  ('E01', 'AAGACGGA', 'Illumina', 'SureSelect XT2'),
  ('E02', 'CGAACTTA', 'Illumina', 'SureSelect XT2'),
  ('E03', 'ACCTCCAA', 'Illumina', 'SureSelect XT2'),
  ('E04', 'CTGTAGCC', 'Illumina', 'SureSelect XT2'),
  ('E05', 'CGCTGATC', 'Illumina', 'SureSelect XT2'),
  ('E06', 'ATTGAGGA', 'Illumina', 'SureSelect XT2'),
  ('E07', 'CCGTGAGA', 'Illumina', 'SureSelect XT2'),
  ('E08', 'CATACCAA', 'Illumina', 'SureSelect XT2'),
  ('E09', 'AGATGTAC', 'Illumina', 'SureSelect XT2'),
  ('E10', 'CAACCACA', 'Illumina', 'SureSelect XT2'),
  ('E11', 'CCTCCTGA', 'Illumina', 'SureSelect XT2'),
  ('E12', 'ACACAGAA', 'Illumina', 'SureSelect XT2'),
  ('F01', 'GACTAGTA', 'Illumina', 'SureSelect XT2'),
  ('F02', 'GATAGACA', 'Illumina', 'SureSelect XT2'),
  ('F03', 'GCGAGTAA', 'Illumina', 'SureSelect XT2'),
  ('F04', 'GCTCGGTA', 'Illumina', 'SureSelect XT2'),
  ('F05', 'GGTGCGAA', 'Illumina', 'SureSelect XT2'),
  ('F06', 'GTCGTAGA', 'Illumina', 'SureSelect XT2'),
  ('F07', 'GTGTTCTA', 'Illumina', 'SureSelect XT2'),
  ('F08', 'TATCAGCA', 'Illumina', 'SureSelect XT2'),
  ('F09', 'TCTTCACA', 'Illumina', 'SureSelect XT2'),
  ('F10', 'TGGAACAA', 'Illumina', 'SureSelect XT2'),
  ('F11', 'TGGTGGTA', 'Illumina', 'SureSelect XT2'),
  ('F12', 'GAACAGGC', 'Illumina', 'SureSelect XT2'),
  ('G01', 'ATTGGCTC', 'Illumina', 'SureSelect XT2'),
  ('G02', 'AAGGACAC', 'Illumina', 'SureSelect XT2'),
  ('G03', 'ACTATGCA', 'Illumina', 'SureSelect XT2'),
  ('G04', 'ACACGACC', 'Illumina', 'SureSelect XT2'),
  ('G05', 'CCTAATCC', 'Illumina', 'SureSelect XT2'),
  ('G06', 'AGAGTCAA', 'Illumina', 'SureSelect XT2'),
  ('G07', 'CAATGGAA', 'Illumina', 'SureSelect XT2'),
  ('G08', 'ATAGCGAC', 'Illumina', 'SureSelect XT2'),
  ('G09', 'CCGAAGTA', 'Illumina', 'SureSelect XT2'),
  ('G10', 'CCTCTATC', 'Illumina', 'SureSelect XT2'),
  ('G11', 'AACAACCA', 'Illumina', 'SureSelect XT2'),
  ('G12', 'AACCGAGA', 'Illumina', 'SureSelect XT2'),
  ('H01', 'GATGAATC', 'Illumina', 'SureSelect XT2'),
  ('H02', 'GACAGTGC', 'Illumina', 'SureSelect XT2'),
  ('H03', 'CGGATTGC', 'Illumina', 'SureSelect XT2'),
  ('H04', 'AGTCACTA', 'Illumina', 'SureSelect XT2'),
  ('H05', 'CTGAGCCA', 'Illumina', 'SureSelect XT2'),
  ('H06', 'CCGACAAC', 'Illumina', 'SureSelect XT2'),
  ('H07', 'AGCACCTC', 'Illumina', 'SureSelect XT2'),
  ('H08', 'ACGCTCGA', 'Illumina', 'SureSelect XT2'),
  ('H09', 'CGCATACA', 'Illumina', 'SureSelect XT2'),
  ('H10', 'ACAGATTC', 'Illumina', 'SureSelect XT2'),
  ('H11', 'AATCCGTC', 'Illumina', 'SureSelect XT2'),
  ('H12', 'ACAAGCTA', 'Illumina', 'SureSelect XT2'),
  ("01", "CGATGT", "Illumina", "NEXTflex 6bp"),
  ("02", "TGACCA", "Illumina", "NEXTflex 6bp"),
  ("03", "ACAGTG", "Illumina", "NEXTflex 6bp"),
  ("04", "GCCAAT", "Illumina", "NEXTflex 6bp"),
  ("05", "CAGATC", "Illumina", "NEXTflex 6bp"),
  ("06", "CTTGTA", "Illumina", "NEXTflex 6bp"),
  ("07", "ATCACG", "Illumina", "NEXTflex 6bp"),
  ("08", "TTAGGC", "Illumina", "NEXTflex 6bp"),
  ("09", "ACTTGA", "Illumina", "NEXTflex 6bp"),
  ("10", "GATCAG", "Illumina", "NEXTflex 6bp"),
  ("11", "TAGCTT", "Illumina", "NEXTflex 6bp"),
  ("12", "GGCTAC", "Illumina", "NEXTflex 6bp"),
  ("13", "AGTCAA", "Illumina", "NEXTflex 6bp"),
  ("14", "AGTTCC", "Illumina", "NEXTflex 6bp"),
  ("15", "ATGTCA", "Illumina", "NEXTflex 6bp"),
  ("16", "CCGTCC", "Illumina", "NEXTflex 6bp"),
  ("17", "GTAGAG", "Illumina", "NEXTflex 6bp"),
  ("18", "GTCCGC", "Illumina", "NEXTflex 6bp"),
  ("19", "GTGAAA", "Illumina", "NEXTflex 6bp"),
  ("20", "GTGGCC", "Illumina", "NEXTflex 6bp"),
  ("21", "GTTTCG", "Illumina", "NEXTflex 6bp"),
  ("22", "CGTACG", "Illumina", "NEXTflex 6bp"),
  ("23", "GAGTGG", "Illumina", "NEXTflex 6bp"),
  ("24", "GGTAGC", "Illumina", "NEXTflex 6bp"),
  ("25", "ACTGAT", "Illumina", "NEXTflex 6bp"),
  ("26", "ATGAGC", "Illumina", "NEXTflex 6bp"),
  ("27", "ATTCCT", "Illumina", "NEXTflex 6bp"),
  ("28", "CAAAAG", "Illumina", "NEXTflex 6bp"),
  ("29", "CAACTA", "Illumina", "NEXTflex 6bp"),
  ("30", "CACCGG", "Illumina", "NEXTflex 6bp"),
  ("31", "CACGAT", "Illumina", "NEXTflex 6bp"),
  ("32", "CACTCA", "Illumina", "NEXTflex 6bp"),
  ("33", "CAGGCG", "Illumina", "NEXTflex 6bp"),
  ("34", "CATGGC", "Illumina", "NEXTflex 6bp"),
  ("35", "CATTTT", "Illumina", "NEXTflex 6bp"),
  ("36", "CCAACA", "Illumina", "NEXTflex 6bp"),
  ("37", "CGGAAT", "Illumina", "NEXTflex 6bp"),
  ("38", "CTAGCT", "Illumina", "NEXTflex 6bp"),
  ("39", "CTATAC", "Illumina", "NEXTflex 6bp"),
  ("40", "CTCAGA", "Illumina", "NEXTflex 6bp"),
  ("41", "GCGCTA", "Illumina", "NEXTflex 6bp"),
  ("42", "TAATCG", "Illumina", "NEXTflex 6bp"),
  ("43", "TACAGC", "Illumina", "NEXTflex 6bp"),
  ("44", "TATAAT", "Illumina", "NEXTflex 6bp"),
  ("45", "TCATTC", "Illumina", "NEXTflex 6bp"),
  ("46", "TCCCGA", "Illumina", "NEXTflex 6bp"),
  ("47", "TCGAAG", "Illumina", "NEXTflex 6bp"),
  ("48", "TCGGCA", "Illumina", "NEXTflex 6bp");

INSERT INTO QCType (name, description, qcTarget, units) VALUES
  ('Bioanalyzer', 'Measures size of library, including adapters', 'Pool', 'bp'),
  ('qPCR', 'Quantitative PCR', 'Pool', 'mol/&#181;l'),
  ('Tape Station', 'Measures size of library, including adapters', 'Library', 'bp'),
  ('Tape Station', 'Measures size of library, including adapters', 'Pool', 'bp'),
  ('FFPE qPCR', 'Quantitation of FFPE tissue quality', 'Sample', 'Q-ratio'),
  ('Volume Check', 'Measures volume in sample', 'Sample', 'uL'),
  ('Mouse qPCR', 'Measures amount of mouse tissue in sample', 'Sample', '&#37;'),
  ('STR', 'Compares identity of sample against reference', 'Sample', ''),
  ('qcGel', 'Older metric', 'Sample', ''),
  ('RIN', 'RNA Integrity Number', 'Sample', ''),
  ('DV200', 'RNA Integrity Number', 'Sample', '&#37;'),
  ('small RNA &#37;', 'Percentage of small RNA in sample', 'Sample', '&#37;'),
  ('DNAse Treated', 'Yes/No', 'Sample', ''),
  ('Nanodrop', 'For when sample is suspected of contamination', 'Sample', 'ng/&#181;l');

INSERT INTO TissueOrigin (alias, description, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('Ad','Adipose',1,NOW(),1,NOW()),
  ('Ap','Appendix',1,NOW(),1,NOW()),
  ('Ag','Adrenal Gland',1,NOW(),1,NOW()),
  ('Bm','Bone Marrow',1,NOW(),1,NOW()),
  ('Bn','Brain',1,NOW(),1,NOW()),
  ('Br','Breast',1,NOW(),1,NOW()),
  ('Bu','Buccal Cells',1,NOW(),1,NOW()),
  ('Cb','Cord Blood',1,NOW(),1,NOW()),
  ('Cn','Central Nervous System',1,NOW(),1,NOW()),
  ('Du','Duodenum',1,NOW(),1,NOW()),
  ('Es','Esophagus',1,NOW(),1,NOW()),
  ('Fs','Foreskin',1,NOW(),1,NOW()),
  ('Gb','Gallbladder',1,NOW(),1,NOW()),
  ('Hr','Heart',1,NOW(),1,NOW()),
  ('Ki','Kidney',1,NOW(),1,NOW()),
  ('Le','Leukocyte',1,NOW(),1,NOW()),
  ('Li','Large Intestine',1,NOW(),1,NOW()),
  ('Ln','Lymph Node',1,NOW(),1,NOW()),
  ('Lu','Lung',1,NOW(),1,NOW()),
  ('Lv','Liver',1,NOW(),1,NOW()),
  ('Lx','Larynx',1,NOW(),1,NOW()),
  ('Ly','Lymphocyte',1,NOW(),1,NOW()),
  ('Md','Mediastinum',1,NOW(),1,NOW()),
  ('Me','Mesenchyme',1,NOW(),1,NOW()),
  ('Nk','Neck',1,NOW(),1,NOW()),
  ('Oc','Oral Cavity',1,NOW(),1,NOW()),
  ('Om','Omentum',1,NOW(),1,NOW()),
  ('Ov','Ovary',1,NOW(),1,NOW()),
  ('Pa','Pancreas',1,NOW(),1,NOW()),
  ('Pb','Peripheral Blood',1,NOW(),1,NOW()),
  ('Pr','Prostate',1,NOW(),1,NOW()),
  ('Sa','Saliva',1,NOW(),1,NOW()),
  ('Sg','Salivary Gland',1,NOW(),1,NOW()),
  ('Si','Small Intestine',1,NOW(),1,NOW()),
  ('Sk','Skin',1,NOW(),1,NOW()),
  ('Sm','Skeletal Muscle',1,NOW(),1,NOW()),
  ('Sp','Spleen',1,NOW(),1,NOW()),
  ('St','Stomach',1,NOW(),1,NOW()),
  ('Ta','Tail (Referring to Models)',1,NOW(),1,NOW()),
  ('Tr','Trachea',1,NOW(),1,NOW()),
  ('Mu','Muscle',1,NOW(),1,NOW()),
  ('Wm','Worm (Referring to Models)',1,NOW(),1,NOW()),
  ('nn','Unknown',1,NOW(),1,NOW());

INSERT INTO TissueType (alias, description, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('R','Reference or non-tumour, non-diseased tissue sample. Typically used as a donor-specific comparison to a diseased tissue, usually a cancer',1,NOW(),1,NOW()),
  ('P','Primary tumour',1,NOW(),1,NOW()),
  ('M','Metastatic tumour',1,NOW(),1,NOW()),
  ('X','Xenograft derived from some tumour. Note: may not necessarily be a mouse xenograft',1,NOW(),1,NOW()),
  ('T','Unclassifed tumour',1,NOW(),1,NOW()),
  ('C','Cell line derived from a tumour',1,NOW(),1,NOW()),
  ('B','Benign tumour',1,NOW(),1,NOW()),
  ('F','Fibroblast cells',1,NOW(),1,NOW()),
  ('E','Endothelial cells',1,NOW(),1,NOW()),
  ('S','Serum from blood where clotting proteins have been removed',1,NOW(),1,NOW()),
  ('A','Cells taken from Ascites fluid',1,NOW(),1,NOW()),
  ('O','Organoid',1,NOW(),1,NOW());

INSERT INTO TissueType (alias, description, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('Fresh Frozen','Fresh Frozen',1,NOW(),1,NOW()),
  ('FFPE','FFPE',1,NOW(),1,NOW()),
  ('Blood','Blood',1,NOW(),1,NOW());

INSERT INTO SamplePurpose (alias, description, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('CNV','CNV',1,NOW(),1,NOW()),
  ('Extra','Extra',1,NOW(),1,NOW()),
  ('Library','Library',1,NOW(),1,NOW()),
  ('Methylation','Methylation',1,NOW(),1,NOW()),
  ('PacBio','PacBio',1,NOW(),1,NOW()),
  ('Research','Research',1,NOW(),1,NOW()),
  ('Sequenom','Sequenom',1,NOW(),1,NOW()),
  ('Stock','Stock',1,NOW(),1,NOW()),
  ('Validation','Validation',1,NOW(),1,NOW()),
  ('WGA','WGA',1,NOW(),1,NOW());

INSERT INTO QcPassedDetail (status, description, noteRequired, createdBy, creationDate, updatedBy, lastUpdated) VALUES
  ('true','STR Not Submitted',false,1,NOW(),1,NOW()),
  ('true','STR Passed',false,1,NOW(),1,NOW()),
  ('true','OKd by Collaborator',true,1,NOW(),1,NOW()),
  (NULL,NULL,false,1,NOW(),1,NOW()),
  (NULL,'Waiting: Path Report',true,1,NOW(),1,NOW()),
  ('false','Failed STR',true,1,NOW(),1,NOW()),
  ('false','Failed Diagnosis',true,1,NOW(),1,NOW()),
  ('false','Failed QC',true,1,NOW(),1,NOW()),
  ('false','Reference Required',false,1,NOW(),1,NOW()),
  ('false','Refused Consent',false,1,NOW(),1,NOW());

INSERT INTO Institute (alias) VALUES
  ('BioBank','Ontario Institute for Cancer Research');
  ('BioBank','University Health Network');
  ('Brad Wouters','University Health Network');
  ('Catherine OBrien','University Health Network');
  ('John Bell','Ontario Institute for Cancer Research');
  ('Ming Tsao','University Health Network');
  ('Not Specified','Kingston General Hospital');
  ('Not Specified','Massachusetts General Hospital');
  ('Not Specified','Mayo Clinic');
  ('Not Specified','Ontario Institute for Cancer Research');
  ('Not Specified','OPCS');
  ('Not Specified','Ottawa Hospital Research Institute');
  ('Not Specified','Sheba Medical Center');
  ('Not Specified','St Josephs Healthcare Hamilton');
  ('Not Specified','St Josephs Health Centre (Toronto)');
  ('Not Specified','Sunnybrook Health Sciences Centre');
  ('Not Specified','UHN McGill');
  ('Not Specified','University Health Network');
  ('Not Specified','University of Nebraska Medical Center');
  ('Pathology','Ontario Institute for Cancer Research');
  ('Steve Gallinger','Sunnybrook Health Sciences Centre');
  ('Steve Gallinger','University Health Network');

