INSERT INTO LibraryDesign(name, sampleClassId, libraryType, librarySelectionType, libraryStrategyType, suffix) VALUES
  ('WG', (SELECT sampleClassId FROM SampleClass WHERE sampleCategory = 'Analyte' AND alias = 'gDNA (stock)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Paired End'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'PCR'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'WGS'), '_WG'),
  ('TS (Hybrid Selection)', (SELECT sampleClassId FROM SampleClass WHERE sampleCategory = 'Analyte' AND alias = 'gDNA (stock)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Paired End'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'Hybrid Selection'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'AMPLICON'), '_TS'),
  ('TS (PCR)', (SELECT sampleClassId FROM SampleClass WHERE sampleCategory = 'Analyte' AND alias = 'gDNA (stock)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Paired End'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'PCR'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'AMPLICON'), '_TS'),
  ('EX', (SELECT sampleClassId FROM SampleClass WHERE sampleCategory = 'Analyte' AND alias = 'gDNA (stock)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Paired End'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'Hybrid Selection'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'WXS'), '_EX'),
  ('SM', (SELECT sampleClassId FROM SampleClass WHERE sampleCategory = 'Analyte' AND alias = 'cDNA (stock)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Small RNA'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'size fractionation'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'RNA-Seq'), '_SM'),
  ('WT', (SELECT sampleClassId FROM SampleClass WHERE sampleCategory = 'Analyte' AND alias = 'cDNA (stock)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Whole Transcriptome'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'cDNA'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'RNA-Seq'), '_WT'),
  ('MR', (SELECT sampleClassId FROM SampleClass WHERE sampleCategory = 'Analyte' AND alias = 'cDNA (stock)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'mRNA Seq'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'cDNA'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'RNA-Seq'), '_WT'),
  ('CH', (SELECT sampleClassId FROM SampleClass WHERE sampleCategory = 'Analyte' AND alias = 'gDNA (stock)'), (SELECT libraryTypeId FROM LibraryType WHERE platformType = 'Illumina' AND description = 'Single End'), (SELECT librarySelectionTypeId FROM LibrarySelectionType WHERE name = 'ChIP'), (SELECT libraryStrategyTypeId FROM LibraryStrategyType WHERE name = 'ChIP-Seq'), '_CH');
