ALTER TABLE Sample ADD COLUMN distributed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE Sample ADD COLUMN distributionDate DATE DEFAULT NULL;
ALTER TABLE Sample ADD COLUMN distributionRecipient VARCHAR(250) DEFAULT NULL;

ALTER TABLE Library ADD COLUMN distributed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE Library ADD COLUMN distributionDate DATE DEFAULT NULL;
ALTER TABLE Library ADD COLUMN distributionRecipient VARCHAR(250) DEFAULT NULL;