ALTER TABLE Sample MODIFY COLUMN initialVolume DECIMAL(16,10);
ALTER TABLE Sample MODIFY COLUMN volume DECIMAL(16,10);
ALTER TABLE Sample MODIFY COLUMN volumeUsed DECIMAL(16,10);

ALTER TABLE Library MODIFY COLUMN initialVolume DECIMAL(16,10);
ALTER TABLE Library MODIFY COLUMN volume DECIMAL(16,10);
ALTER TABLE Library MODIFY COLUMN volumeUsed DECIMAL(16,10);

ALTER TABLE LibraryAliquot MODIFY COLUMN volume DECIMAL(16,10);
ALTER TABLE LibraryAliquot MODIFY COLUMN volumeUsed DECIMAL(16,10);

ALTER TABLE Pool MODIFY COLUMN volume DECIMAL(16,10);
