DROP PROCEDURE IF EXISTS deleteContainer;
DROP PROCEDURE IF EXISTS deleteLibrary;
DROP PROCEDURE IF EXISTS deleteLibraryAliquot;
DROP PROCEDURE IF EXISTS deletePool;
DROP PROCEDURE IF EXISTS deleteRun;
DROP PROCEDURE IF EXISTS deleteSample;
