ALTER TABLE SampleClass ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE SampleType ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE SampleClass ADD COLUMN directCreationAllowed BOOLEAN DEFAULT 1;
