-- StartNoTest
-- Disable "x does not exist" warnings
SET sql_notes = 0;

DROP TRIGGER IF EXISTS LibraryAdditionalInfoChange;
DROP TRIGGER IF EXISTS BeforeInsertLibrary;
DROP TRIGGER IF EXISTS BeforeInsertPool;
DROP TRIGGER IF EXISTS RunChangePacBio;
DROP TRIGGER IF EXISTS SampleAdditionalInfoChange;
DROP TRIGGER IF EXISTS SampleCVSlideChange;
DROP TRIGGER IF EXISTS BeforeInsertSample;
DROP TRIGGER IF EXISTS LibraryAdditionalInfoChange;
DROP TRIGGER IF EXISTS PlateChange;
DROP TRIGGER IF EXISTS PlateInsert;
DROP TRIGGER IF EXISTS SampleLCMTubeChange;
DROP TRIGGER IF EXISTS StatusChange;

DROP FUNCTION IF EXISTS `nextval`;
DROP PROCEDURE IF EXISTS moveBoxItem;
DROP PROCEDURE IF EXISTS removeBoxItem;
DROP VIEW IF EXISTS BoxableView;

DROP PROCEDURE IF EXISTS addBoxSize;
DROP PROCEDURE IF EXISTS addBoxUse;
DROP PROCEDURE IF EXISTS addContainerModel;
DROP PROCEDURE IF EXISTS addIndex;
DROP PROCEDURE IF EXISTS addIndexFamily;
DROP PROCEDURE IF EXISTS addInstitute;
DROP PROCEDURE IF EXISTS addInstrument;
DROP PROCEDURE IF EXISTS addInstrumentModel;
DROP PROCEDURE IF EXISTS addKitDescriptor;
DROP PROCEDURE IF EXISTS addLab;
DROP PROCEDURE IF EXISTS addLibraryDesign;
DROP PROCEDURE IF EXISTS addLibraryDesignCode;
DROP PROCEDURE IF EXISTS addLibraryType;
DROP PROCEDURE IF EXISTS addQcType;
DROP PROCEDURE IF EXISTS addReferenceGenome;
DROP PROCEDURE IF EXISTS addSamplePurpose;
DROP PROCEDURE IF EXISTS addSequencingParameters;
DROP PROCEDURE IF EXISTS addTargetedSequencing;
DROP PROCEDURE IF EXISTS addTissueMaterial;
DROP PROCEDURE IF EXISTS addTissueOrigin;
DROP PROCEDURE IF EXISTS addTissueType;
DROP PROCEDURE IF EXISTS deleteContainer;
DROP PROCEDURE IF EXISTS deleteLibrary;
DROP PROCEDURE IF EXISTS deleteLibraryAliquot;
DROP PROCEDURE IF EXISTS deletePool;
DROP PROCEDURE IF EXISTS deleteRun;
DROP PROCEDURE IF EXISTS deleteSample;

SET sql_notes = 1;
-- EndNoTest
