ALTER TABLE ContainerQC ADD created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ContainerQC ADD lastModified timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE LibraryQC ADD created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE LibraryQC ADD lastModified timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE PoolQC ADD created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE PoolQC ADD lastModified timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE SampleQC ADD created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE SampleQC ADD lastModified timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
