ALTER TABLE Printer MODIFY layout varchar(2048) NOT NULL;
ALTER TABLE Printer ADD COLUMN height DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE Printer ADD COLUMN width DOUBLE NOT NULL DEFAULT 0;

UPDATE Printer SET width = 8.3, height = 7.7 WHERE layout = 'AVERY_8363';
UPDATE Printer SET width = 12, height = 38 WHERE layout = 'BPT_635_488';
UPDATE Printer SET width = 14, height = 4.666 WHERE layout = 'JTT_183';
UPDATE Printer SET width = 8.3, height = 4.08 WHERE layout LIKE 'JTT_7%';
UPDATE Printer SET width = 41, height = 15 WHERE layout LIKE 'THT_155_490%';
UPDATE Printer SET width = 25, height = 25 WHERE layout = 'THT_179_492';
UPDATE Printer SET width = 22.86, height =  19.05 WHERE layout = 'FTT_152C1_1WH';
UPDATE Printer SET width = 38, height = 12 WHERE layout = 'THT_181_492_3';

UPDATE Printer SET layout = '[{"contents":{"use":"BARCODE"},"element":"2dbarcode","moduleSize":0.125,"x":1.75,"y":1.75},{"contents":{"use":"DATE"},"element":"text","height":0.8,"x":0.5,"y":7.125},{"contents":{"use":"ALIAS"},"element":"text","height":0.8,"lineLimit":15,"x":2.4,"y":7.125}]' WHERE layout = 'AVERY_8363';
UPDATE Printer SET layout = '[{"contents":{"use":"BARCODE_BASE64"},"element":"2dbarcode","height":0.21,"x":2,"y":6},{"contents":{"use":"BARCODE_BASE64"},"element":"2dbarcode","height":0.25,"x":13,"y":1},{"contents":{"use":"LABEL_TEXT"},"element":"text","height":1.4,"lineLimit":20,"x":29,"y":2},{"contents":{"use":"LABEL_TEXT"},"element":"text","height":2,"lineLimit":20,"x":17,"y":8},{"contents":{"use":"NAME"},"element":"text","height":2,"x":17,"y":11}]' WHERE layout = 'BPT_635_488';
UPDATE Printer SET layout = '[{"contents":{"use":"ALIAS"},"element":"textblock","height":0.5,"lineLimit":8,"rowLimit":2,"x":10.7,"y":2.3},{"contents":{"use":"ALIAS"},"element":"textblock","height":0.8,"lineLimit":18,"rowLimit":2,"x":1,"y":1.375},{"contents":[{"use":"DATE"},{"use":"DESCRIPTION"}],"element":"textblock","height":0.8,"lineLimit":12,"rowLimit":2,"x":1,"y":3.375},{"contents":{"use":"ALIAS"},"element":"2dbarcode","height":0.1,"x":6.78,"y":4}]' WHERE layout = 'JTT_183';
UPDATE Printer SET layout = '[{"contents":{"use":"ALIAS"},"element":"2dbarcode","moduleSize":0.1,"x":5.78,"y":3.8},{"contents":[{"use":"DATE"},{"use":"DESCRIPTION"}],"element":"textblock","height":0.8,"lineLimit":12,"rowLimit":2,"x":0.3,"y":3},{"contents":{"use":"ALIAS"},"element":"textblock","height":0.8,"lineLimit":18,"rowLimit":2,"x":0.3,"y":1}]' WHERE layout = 'JTT_7';
UPDATE Printer SET layout = '[{"contents":{"use":"ALIAS"},"element":"2dbarcode","moduleSize":0.1,"x":5.78,"y":3.8},{"contents":[{"use":"DATE"},{"use":"GROUP_DESC"}],"element":"textblock","height":0.8,"lineLimit":12,"rowLimit":2,"x":0.3,"y":3},{"contents":{"use":"ALIAS"},"element":"textblock","height":0.8,"lineLimit":18,"rowLimit":2,"x":0.3,"y":1}]' WHERE layout = 'JTT_7_GROUPDESC';
UPDATE Printer SET layout = '[{"contents":{"use":"ALIAS"},"element":"2dbarcode","moduleSize":0.1,"x":5.78,"y":3.8},{"contents":[{"use":"DATE"},{"use":"CONCENTRATION"}],"element":"textblock","height":0.8,"lineLimit":12,"rowLimit":2,"x":0.3,"y":3},{"contents":{"use":"ALIAS"},"element":"textblock","height":0.8,"lineLimit":18,"rowLimit":2,"x":0.3,"y":1}]' WHERE layout = 'JTT_7S';
UPDATE Printer SET layout = '[{"contents":{"use":"BARCODE"},"element":"2dbarcode","moduleSize":0.3,"x":2,"y":2},{"contents":{"use":"NAME"},"element":"text","height":3,"lineLimit":12,"style":"BOLD","x":7,"y":3},{"contents":[{"use":"LABEL_TEXT"},{"use":"CONCENTRATION"}],"element":"textblock","height":2,"lineLimit":28,"rowLimit":5,"x":7,"y":5}]' WHERE layout = 'THT_155_490';
UPDATE Printer SET layout = '[{"contents":{"use":"NAME"},"direction":"VERTICAL_UP","element":"text","height":2,"lineLimit":10,"x":9,"y":12},{"contents":[{"use":"LABEL_TEXT"},{"use":"CONCENTRATION"},{"use":"DESCRIPTION"}],"direction":"VERTICAL_UP","element":"textblock","height":2,"lineLimit":9,"rowLimit":7,"x":11,"y":12}]' WHERE layout = 'THT_155_490T';
UPDATE Printer SET layout = '[{"contents":{"use":"BARCODE"},"element":"2dbarcode","moduleSize":0.3,"x":11,"y":12},{"contents":[{"use":"LABEL_TEXT"},{"use":"DATE"}],"element":"textblock","height":2,"lineLimit":14,"rowLimit":3,"x":2,"y":4}]' WHERE layout = 'THT_179_492';
UPDATE Printer SET layout = '[{"contents":{"use":"BARCODE"},"element":"2barcode","moduleSize":0.3,"x":3,"y":12},{"contents":[{"use":"LABEL_TEXT"},{"use":"DATE"}],"element":"textblock","height":1.8,"lineLimit":14,"rowLimit":3,"x":0,"y":5}]' WHERE layout = 'FTT_152C1_1WH';
UPDATE Printer SET layout = '[{"contents":{"use":"BARCODE_BASE64"},"element":"2barcode","moduleSize":0.21,"x":3,"y":2},{"contents":{"use":"BARCODE_BASE64"},"element":"2barcode","moduleSize":0.25,"x":17,"y":1},{"contents":{"use":"NAME"},"element":"text","height":1.4,"lineLimit":17,"x":29,"y":2},{"contents":{"use":"ALIAS"},"element":"text","height":2,"style":"BOLD","x":17,"y":8},{"contents":{"use":"NAME"},"element":"text","height":2,"style":"BOLD","x":17,"y":11},{"contents":{"use":"ALIAS"},"element":"text","height":2,"lineLimit":17,"x":17,"y":8},{"contents":{"use":"NAME"},"element":"text","height":2,"style":"BOLD","x":17,"y":11}]' WHERE layout = 'THT_181_492_3';
