version: '3.7'

services:
  db:
    volumes:
      - "miso_plain_db:/var/lib/mysql"
  
  flyway:
    volumes:
      - "./.docker/detailed_sample_config/V0792__detailed_sample_data.sql:/flyway/sql/V0792__detailed_sample_data.sql"

  webapp:
    volumes:
      - "miso_files:/storage/miso/files/"

volumes:
  miso_plain_db:
  miso_files:
