version: '3.7'

services:
  flyway:
    environment:
      MISO_DB_USER: ${MISO_DB_USER}
      MISO_DB: ${MISO_DB}
      MISO_DB_HOST_PORT: 'db:3306'
      MISO_DB_PASS_FILE: /run/secrets/lims_password
      MISO_FILES_DIR: /storage/miso/files/
      
  webapp:
    environment:
      MISO_DB: ${MISO_DB}
      MISO_DB_USER: ${MISO_DB_USER}
      MISO_DB_PASS_FILE: /run/secrets/lims_password
      MISO_DB_HOST_PORT: 'db:3306'