rootLogger.level = info
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT

appender.console.type = Console
appender.console.name = STDOUT
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %p: %m%n

#logger.hibernateSql.name = org.hibernate.SQL
#logger.hibernateSql.level = debug
#logger.hibernateType.name = org.hibernate.type.descriptor.sql
#logger.hibernateType.level = trace
logger.hibernateDeprecation.name = org.hibernate.orm.deprecation
logger.hibernateDeprecation.level = error

# enable for troubleshooting box scanners
#logger.visionmate.name = ca.on.oicr.gsi.visionmate
#logger.visionmate.level = debug

