version: '3.7'

################################################################################
# Brings up a MISO LIMS environment in detailed sample mode.
#
# Intended for demo purposes only. NOT INTENDED FOR PRODUCTION USE.
# See the docs for more information: https://miso-lims.github.io/miso-lims/
#
#
# Environment variables must be provided for this file to work.
# The .env file or shell environment variables contain:
# the following:
# * MISO_DB_USER : name of the MySQL user who accesses MISO_DB
# * MISO_DB : name of the LIMS Db in MySql
# * MISO_DB_PASSWORD_FILE : path to the file with the password to the MySQL DB for user MISO_DB_USER
# * MISO_TAG : tag of the MISO Docker containers (migration and webapp)
#
################################################################################
# USAGE :
# wget https://github.com/miso-lims/miso-lims/archive/master.zip
# unzip master.zip 'miso-lims-master/.docker/*' && mv miso-lims-master/.docker miso-lims-compose && rm -r master.zip miso-lims-master/
# cd miso-lims-compose
# export MISO_DB_USER=tgaclims MISO_DB=lims MISO_DB_PASSWORD_FILE=./.miso_db_password MISO_TAG=latest
# echo "changeme" > ./.miso_db_password
# docker-compose -f demo.detailed.yml up
#
################################################################################
# Code available at https://github.com/miso-lims/miso-lims under GPL-3.0
################################################################################

secrets:
  lims_password:
    file: ${MISO_DB_PASSWORD_FILE}
  root_password:
    file: ${MISO_DB_ROOT_PASSWORD_FILE}

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_password
      MYSQL_DATABASE: ${MISO_DB}
      MYSQL_USER: ${MISO_DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/lims_password
    secrets:
      - root_password
      - lims_password

  flyway:
    image: ghcr.io/miso-lims/miso-lims-migration:${MISO_TAG}
    command: migrate
    secrets:
      - root_password
    links:
      - db
    depends_on:
      - db
    volumes:
      - type: bind
        source: "./detailed_sample_config/V0792__drop-inconvenient-rows.sql"
        target: "/flyway/sql/V0792__drop-inconvenient-rows.sql"
      - type: bind
        source: "./detailed_sample_config/V0793__detailed_sample_data.sql"
        target: "/flyway/sql/V0793__detailed_sample_data.sql"

  webapp:
    image: ghcr.io/miso-lims/miso-lims-webapp:${MISO_TAG}
    restart: always
    secrets:
      - lims_password
    links:
      - db
    depends_on:
      - db
    volumes:
      - type: bind
        source: "./detailed_sample_config/miso.properties"
        target: "/usr/local/tomcat/conf/Catalina/localhost/miso.properties"


  nginx:
    image: nginx:1.15.12-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: "./nginx/http.conf"
        target: "/etc/nginx/conf.d/default.conf"
    links:
      - webapp
    depends_on:
      - webapp
