#!/usr/bin/env bash

# Runs flyway and whatever provided command against the MISO DB that is set up with this container
# Relies on environment variables: MISO_DB_HOST_PORT, MISO_DB, MISO_FILES_DIR, FLYWAY_USER, FLYWAY_PASSWORD_FILE
# the first argument given to this script is passed fully onto the flyway command
# e.g.  
#   run-flyway migrate : applies all of the migrations on the classpath and in /flyway/migrations
#   run-flyway clean : rolls back changes

export FLYWAY_PASSWORD=$(cat ${FLYWAY_PASSWORD_FILE})

# note: MySQL useSSL option is deprecated in favour of sslMode, but included here because Flyway shows a warning otherwise
command="flyway -url='jdbc:mysql://${MISO_DB_HOST_PORT}/${MISO_DB}?autoReconnect=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&sslMode=DISABLED&connectionTimeZone=SERVER&cacheDefaultTimeZone=false&useSSL=false' \
  -locations='filesystem:/flyway/sql,classpath:/uk/ac/bbsrc/tgac/miso/db/migration' \
  -outOfOrder=true -ignoreMigrationPatterns='*:missing' -placeholders.filesDir='${MISO_FILES_DIR}' \
  -connectRetries=60"

eval "${command} $1"

rc=$?; if [[ $rc != 0 ]]
then
	"run-flyway command $1 failed with exit : $rc"
fi
exit $rc; 

