.TH runscanner-illumina 1 "Jul 2017" "1.0" "USER COMMANDS"
.SH NAME 
runscanner-illumina \- Process an Illumina directory for MISO's Run Scanner
.SH SYNOPSIS
.B runscanner-illumina
.I directory
.SH DESCRIPTION
This program is meant to extract run information from an Illumina sequencer's output directory in a form that is useable by Run Scanner. It is not meant to be used directly.
