-- StartNoTest
DROP FUNCTION IF EXISTS `nextval`;
DROP TRIGGER IF EXISTS PlateChange;
DROP TRIGGER IF EXISTS PlateInsert;
DROP TRIGGER IF EXISTS StatusChange;
DROP PROCEDURE IF EXISTS moveBoxItem;
DROP PROCEDURE IF EXISTS removeBoxItem;
DROP VIEW IF EXISTS BoxableView;
-- EndNoTest
