-- StartNoTest
UPDATE IndexFamily SET platformType = 'ILLUMINA' WHERE name = '454' AND platformType = 'LS454';

CALL addIndexFamily('10X Family', 'ILLUMINA', FALSE);
-- Non-sequences used here because analysis handles these based on their name
CALL addIndex('10X Family', 'SI-GA-A1', 'SI-GA-A1', 1);
CALL addIndex('10X Family', 'SI-GA-A2', 'SI-GA-A2', 1);
CALL addIndex('10X Family', 'SI-GA-A3', 'SI-GA-A3', 1);
CALL addIndex('10X Family', 'SI-GA-A4', 'SI-GA-A4', 1);
CALL addIndex('10X Family', 'SI-GA-A5', 'SI-GA-A5', 1);
CALL addIndex('10X Family', 'SI-GA-A6', 'SI-GA-A6', 1);
CALL addIndex('10X Family', 'SI-GA-A7', 'SI-GA-A7', 1);
CALL addIndex('10X Family', 'SI-GA-A8', 'SI-GA-A8', 1);
CALL addIndex('10X Family', 'SI-GA-A9', 'SI-GA-A9', 1);
CALL addIndex('10X Family', 'SI-GA-A10', 'SI-GA-A10', 1);
CALL addIndex('10X Family', 'SI-GA-A11', 'SI-GA-A11', 1);
CALL addIndex('10X Family', 'SI-GA-A12', 'SI-GA-A12', 1);
CALL addIndex('10X Family', 'SI-GA-B1', 'SI-GA-B1', 1);
CALL addIndex('10X Family', 'SI-GA-B2', 'SI-GA-B2', 1);
CALL addIndex('10X Family', 'SI-GA-B3', 'SI-GA-B3', 1);
CALL addIndex('10X Family', 'SI-GA-B4', 'SI-GA-B4', 1);
CALL addIndex('10X Family', 'SI-GA-B5', 'SI-GA-B5', 1);
CALL addIndex('10X Family', 'SI-GA-B6', 'SI-GA-B6', 1);
CALL addIndex('10X Family', 'SI-GA-B7', 'SI-GA-B7', 1);
CALL addIndex('10X Family', 'SI-GA-B8', 'SI-GA-B8', 1);
CALL addIndex('10X Family', 'SI-GA-B9', 'SI-GA-B9', 1);
CALL addIndex('10X Family', 'SI-GA-B10', 'SI-GA-B10', 1);
CALL addIndex('10X Family', 'SI-GA-B11', 'SI-GA-B11', 1);
CALL addIndex('10X Family', 'SI-GA-B12', 'SI-GA-B12', 1);
CALL addIndex('10X Family', 'SI-GA-C1', 'SI-GA-C1', 1);
CALL addIndex('10X Family', 'SI-GA-C2', 'SI-GA-C2', 1);
CALL addIndex('10X Family', 'SI-GA-C3', 'SI-GA-C3', 1);
CALL addIndex('10X Family', 'SI-GA-C4', 'SI-GA-C4', 1);
CALL addIndex('10X Family', 'SI-GA-C5', 'SI-GA-C5', 1);
CALL addIndex('10X Family', 'SI-GA-C6', 'SI-GA-C6', 1);
CALL addIndex('10X Family', 'SI-GA-C7', 'SI-GA-C7', 1);
CALL addIndex('10X Family', 'SI-GA-C8', 'SI-GA-C8', 1);
CALL addIndex('10X Family', 'SI-GA-C9', 'SI-GA-C9', 1);
CALL addIndex('10X Family', 'SI-GA-C10', 'SI-GA-C10', 1);
CALL addIndex('10X Family', 'SI-GA-C11', 'SI-GA-C11', 1);
CALL addIndex('10X Family', 'SI-GA-C12', 'SI-GA-C12', 1);
CALL addIndex('10X Family', 'SI-GA-D1', 'SI-GA-D1', 1);
CALL addIndex('10X Family', 'SI-GA-D2', 'SI-GA-D2', 1);
CALL addIndex('10X Family', 'SI-GA-D3', 'SI-GA-D3', 1);
CALL addIndex('10X Family', 'SI-GA-D4', 'SI-GA-D4', 1);
CALL addIndex('10X Family', 'SI-GA-D5', 'SI-GA-D5', 1);
CALL addIndex('10X Family', 'SI-GA-D6', 'SI-GA-D6', 1);
CALL addIndex('10X Family', 'SI-GA-D7', 'SI-GA-D7', 1);
CALL addIndex('10X Family', 'SI-GA-D8', 'SI-GA-D8', 1);
CALL addIndex('10X Family', 'SI-GA-D9', 'SI-GA-D9', 1);
CALL addIndex('10X Family', 'SI-GA-D10', 'SI-GA-D10', 1);
CALL addIndex('10X Family', 'SI-GA-D11', 'SI-GA-D11', 1);
CALL addIndex('10X Family', 'SI-GA-D12', 'SI-GA-D12', 1);
CALL addIndex('10X Family', 'SI-GA-E1', 'SI-GA-E1', 1);
CALL addIndex('10X Family', 'SI-GA-E2', 'SI-GA-E2', 1);
CALL addIndex('10X Family', 'SI-GA-E3', 'SI-GA-E3', 1);
CALL addIndex('10X Family', 'SI-GA-E4', 'SI-GA-E4', 1);
CALL addIndex('10X Family', 'SI-GA-E5', 'SI-GA-E5', 1);
CALL addIndex('10X Family', 'SI-GA-E6', 'SI-GA-E6', 1);
CALL addIndex('10X Family', 'SI-GA-E7', 'SI-GA-E7', 1);
CALL addIndex('10X Family', 'SI-GA-E8', 'SI-GA-E8', 1);
CALL addIndex('10X Family', 'SI-GA-E9', 'SI-GA-E9', 1);
CALL addIndex('10X Family', 'SI-GA-E10', 'SI-GA-E10', 1);
CALL addIndex('10X Family', 'SI-GA-E11', 'SI-GA-E11', 1);
CALL addIndex('10X Family', 'SI-GA-E12', 'SI-GA-E12', 1);
CALL addIndex('10X Family', 'SI-GA-F1', 'SI-GA-F1', 1);
CALL addIndex('10X Family', 'SI-GA-F2', 'SI-GA-F2', 1);
CALL addIndex('10X Family', 'SI-GA-F3', 'SI-GA-F3', 1);
CALL addIndex('10X Family', 'SI-GA-F4', 'SI-GA-F4', 1);
CALL addIndex('10X Family', 'SI-GA-F5', 'SI-GA-F5', 1);
CALL addIndex('10X Family', 'SI-GA-F6', 'SI-GA-F6', 1);
CALL addIndex('10X Family', 'SI-GA-F7', 'SI-GA-F7', 1);
CALL addIndex('10X Family', 'SI-GA-F8', 'SI-GA-F8', 1);
CALL addIndex('10X Family', 'SI-GA-F9', 'SI-GA-F9', 1);
CALL addIndex('10X Family', 'SI-GA-F10', 'SI-GA-F10', 1);
CALL addIndex('10X Family', 'SI-GA-F11', 'SI-GA-F11', 1);
CALL addIndex('10X Family', 'SI-GA-F12', 'SI-GA-F12', 1);
CALL addIndex('10X Family', 'SI-GA-G1', 'SI-GA-G1', 1);
CALL addIndex('10X Family', 'SI-GA-G2', 'SI-GA-G2', 1);
CALL addIndex('10X Family', 'SI-GA-G3', 'SI-GA-G3', 1);
CALL addIndex('10X Family', 'SI-GA-G4', 'SI-GA-G4', 1);
CALL addIndex('10X Family', 'SI-GA-G5', 'SI-GA-G5', 1);
CALL addIndex('10X Family', 'SI-GA-G6', 'SI-GA-G6', 1);
CALL addIndex('10X Family', 'SI-GA-G7', 'SI-GA-G7', 1);
CALL addIndex('10X Family', 'SI-GA-G8', 'SI-GA-G8', 1);
CALL addIndex('10X Family', 'SI-GA-G9', 'SI-GA-G9', 1);
CALL addIndex('10X Family', 'SI-GA-G10', 'SI-GA-G10', 1);
CALL addIndex('10X Family', 'SI-GA-G11', 'SI-GA-G11', 1);
CALL addIndex('10X Family', 'SI-GA-G12', 'SI-GA-G12', 1);
CALL addIndex('10X Family', 'SI-GA-H1', 'SI-GA-H1', 1);
CALL addIndex('10X Family', 'SI-GA-H2', 'SI-GA-H2', 1);
CALL addIndex('10X Family', 'SI-GA-H3', 'SI-GA-H3', 1);
CALL addIndex('10X Family', 'SI-GA-H4', 'SI-GA-H4', 1);
CALL addIndex('10X Family', 'SI-GA-H5', 'SI-GA-H5', 1);
CALL addIndex('10X Family', 'SI-GA-H6', 'SI-GA-H6', 1);
CALL addIndex('10X Family', 'SI-GA-H7', 'SI-GA-H7', 1);
CALL addIndex('10X Family', 'SI-GA-H8', 'SI-GA-H8', 1);
CALL addIndex('10X Family', 'SI-GA-H9', 'SI-GA-H9', 1);
CALL addIndex('10X Family', 'SI-GA-H10', 'SI-GA-H10', 1);
CALL addIndex('10X Family', 'SI-GA-H11', 'SI-GA-H11', 1);
CALL addIndex('10X Family', 'SI-GA-H12', 'SI-GA-H12', 1);

CALL addIndexFamily('NEB Index Primer Set 3', 'ILLUMINA', FALSE);

CALL addIndex('NEB Index Primer Set 3', 'Index 17', 'GTAGAG', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 24', 'GGTAGC', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 26', 'ATGAGC', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 28', 'CAAAAG', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 29', 'CAACTA', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 31', 'CACGAT', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 32', 'CACTCA', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 33', 'CAGGCG', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 34', 'CATGGC', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 35', 'CATTTT', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 36', 'CCAACA', 1);
CALL addIndex('NEB Index Primer Set 3', 'Index 42', 'TAATCG', 1);

CALL addIndexFamily('Lexogen i7', 'ILLUMINA', FALSE);

CALL addIndex('Lexogen i7', 'A1', 'CAGCGT', 1);
CALL addIndex('Lexogen i7', 'A2', 'TCAGGA', 1);
CALL addIndex('Lexogen i7', 'A3', 'TCTTAA', 1);
CALL addIndex('Lexogen i7', 'A4', 'TTTATG', 1);
CALL addIndex('Lexogen i7', 'A5', 'AGATAG', 1);
CALL addIndex('Lexogen i7', 'A6', 'CTCTCG', 1);
CALL addIndex('Lexogen i7', 'A7', 'GTGCCA', 1);
CALL addIndex('Lexogen i7', 'A8', 'AGTACT', 1);
CALL addIndex('Lexogen i7', 'A9', 'AAGCTC', 1);
CALL addIndex('Lexogen i7', 'A10', 'GACATC', 1);
CALL addIndex('Lexogen i7', 'A11', 'GCAGCC', 1);
CALL addIndex('Lexogen i7', 'A12', 'CGCGGA', 1);
CALL addIndex('Lexogen i7', 'B1', 'GATCAC', 1);
CALL addIndex('Lexogen i7', 'B2', 'CGGTTA', 1);
CALL addIndex('Lexogen i7', 'B3', 'GTCAGG', 1);
CALL addIndex('Lexogen i7', 'B4', 'AACGCC', 1);
CALL addIndex('Lexogen i7', 'B5', 'TTGGTA', 1);
CALL addIndex('Lexogen i7', 'B6', 'TGACAC', 1);
CALL addIndex('Lexogen i7', 'B7', 'TCGAGG', 1);
CALL addIndex('Lexogen i7', 'B8', 'ATAAGA', 1);
CALL addIndex('Lexogen i7', 'B9', 'GACGAT', 1);
CALL addIndex('Lexogen i7', 'B10', 'CGATCT', 1);
CALL addIndex('Lexogen i7', 'B11', 'ACTCTT', 1);
CALL addIndex('Lexogen i7', 'B12', 'CCTGCT', 1);
CALL addIndex('Lexogen i7', 'C1', 'ACCAGT', 1);
CALL addIndex('Lexogen i7', 'C2', 'TTAACT', 1);
CALL addIndex('Lexogen i7', 'C3', 'ATACTG', 1);
CALL addIndex('Lexogen i7', 'C4', 'CAAGCA', 1);
CALL addIndex('Lexogen i7', 'C5', 'GTTACC', 1);
CALL addIndex('Lexogen i7', 'C6', 'AAGACA', 1);
CALL addIndex('Lexogen i7', 'C7', 'CACTAA', 1);
CALL addIndex('Lexogen i7', 'C8', 'GGTGAG', 1);
CALL addIndex('Lexogen i7', 'C9', 'TCGTTC', 1);
CALL addIndex('Lexogen i7', 'C10', 'CGTCGC', 1);
CALL addIndex('Lexogen i7', 'C11', 'TGCTAT', 1);
CALL addIndex('Lexogen i7', 'C12', 'GCGCTG', 1);
CALL addIndex('Lexogen i7', 'D1', 'TGCACG', 1);
CALL addIndex('Lexogen i7', 'D2', 'ATGAAC', 1);
CALL addIndex('Lexogen i7', 'D3', 'TATGTC', 1);
CALL addIndex('Lexogen i7', 'D4', 'GCTCGA', 1);
CALL addIndex('Lexogen i7', 'D5', 'CGCAAC', 1);
CALL addIndex('Lexogen i7', 'D6', 'ACAGAT', 1);
CALL addIndex('Lexogen i7', 'D7', 'GGTATA', 1);
CALL addIndex('Lexogen i7', 'D8', 'TTCCGC', 1);
CALL addIndex('Lexogen i7', 'D9', 'CCAATT', 1);
CALL addIndex('Lexogen i7', 'D10', 'ATGGCG', 1);
CALL addIndex('Lexogen i7', 'D11', 'AAGTGG', 1);
CALL addIndex('Lexogen i7', 'D12', 'GAACCT', 1);
CALL addIndex('Lexogen i7', 'E1', 'ACATTA', 1);
CALL addIndex('Lexogen i7', 'E2', 'CCTAAG', 1);
CALL addIndex('Lexogen i7', 'E3', 'GAGTCC', 1);
CALL addIndex('Lexogen i7', 'E4', 'GCGAAT', 1);
CALL addIndex('Lexogen i7', 'E5', 'TGGCGA', 1);
CALL addIndex('Lexogen i7', 'E6', 'TAGGCT', 1);
CALL addIndex('Lexogen i7', 'E7', 'CGCCTG', 1);
CALL addIndex('Lexogen i7', 'E8', 'GAAGTG', 1);
CALL addIndex('Lexogen i7', 'E9', 'AGTTGA', 1);
CALL addIndex('Lexogen i7', 'E10', 'ATTGGT', 1);
CALL addIndex('Lexogen i7', 'E11', 'CTCATA', 1);
CALL addIndex('Lexogen i7', 'E12', 'TTCGAG', 1);
CALL addIndex('Lexogen i7', 'F1', 'GTGTAG', 1);
CALL addIndex('Lexogen i7', 'F2', 'AATCCG', 1);
CALL addIndex('Lexogen i7', 'F3', 'GGAGGT', 1);
CALL addIndex('Lexogen i7', 'F4', 'TGGATT', 1);
CALL addIndex('Lexogen i7', 'F5', 'ACCGTG', 1);
CALL addIndex('Lexogen i7', 'F6', 'CTCCAT', 1);
CALL addIndex('Lexogen i7', 'F7', 'AATGAA', 1);
CALL addIndex('Lexogen i7', 'F8', 'CAATGC', 1);
CALL addIndex('Lexogen i7', 'F9', 'AACCGA', 1);
CALL addIndex('Lexogen i7', 'F10', 'GCCACA', 1);
CALL addIndex('Lexogen i7', 'F11', 'CCGACC', 1);
CALL addIndex('Lexogen i7', 'F12', 'AGAATC', 1);
CALL addIndex('Lexogen i7', 'G1', 'CTAGTC', 1);
CALL addIndex('Lexogen i7', 'G2', 'GGCTGC', 1);
CALL addIndex('Lexogen i7', 'G3', 'CACACT', 1);
CALL addIndex('Lexogen i7', 'G4', 'ACCTAC', 1);
CALL addIndex('Lexogen i7', 'G5', 'CAACAG', 1);
CALL addIndex('Lexogen i7', 'G6', 'GCATGG', 1);
CALL addIndex('Lexogen i7', 'G7', 'ACAACG', 1);
CALL addIndex('Lexogen i7', 'G8', 'ACGTCT', 1);
CALL addIndex('Lexogen i7', 'G9', 'CAGATG', 1);
CALL addIndex('Lexogen i7', 'G10', 'CATCTA', 1);
CALL addIndex('Lexogen i7', 'G11', 'GGCCAA', 1);
CALL addIndex('Lexogen i7', 'G12', 'AGGCAT', 1);
CALL addIndex('Lexogen i7', 'H1', 'TGTGCA', 1);
CALL addIndex('Lexogen i7', 'H2', 'TACCTT', 1);
CALL addIndex('Lexogen i7', 'H3', 'CCGCAA', 1);
CALL addIndex('Lexogen i7', 'H4', 'CGAAGG', 1);
CALL addIndex('Lexogen i7', 'H5', 'GATTGT', 1);
CALL addIndex('Lexogen i7', 'H6', 'AATAGC', 1);
CALL addIndex('Lexogen i7', 'H7', 'ATATCC', 1);
CALL addIndex('Lexogen i7', 'H8', 'CAGGAC', 1);
CALL addIndex('Lexogen i7', 'H9', 'GTAGAA', 1);
CALL addIndex('Lexogen i7', 'H10', 'AACAAG', 1);
CALL addIndex('Lexogen i7', 'H11', 'AGACCA', 1);
CALL addIndex('Lexogen i7', 'H12', 'ACACGC', 1);

CALL addIndexFamily('iDES 8bp', 'ILLUMINA', FALSE);

CALL addIndex('iDES 8bp', 'Index 13', 'GAAGCGTT', 1);
CALL addIndex('iDES 8bp', 'Index 14', 'AGTGAGGT', 1);
CALL addIndex('iDES 8bp', 'Index 15', 'TTGGCAGT', 1);
CALL addIndex('iDES 8bp', 'Index 16', 'GCGAATCT', 1);
CALL addIndex('iDES 8bp', 'Index 17', 'CGGTTGTT', 1);
CALL addIndex('iDES 8bp', 'Index 18', 'TAGCTCTG', 1);
CALL addIndex('iDES 8bp', 'Index 19', 'CCTGTATG', 1);
CALL addIndex('iDES 8bp', 'Index 20', 'GATCAAGG', 1);
CALL addIndex('iDES 8bp', 'Index 21', 'GGAGTTAG', 1);
CALL addIndex('iDES 8bp', 'Index 22', 'ATGGTTCC', 1);
CALL addIndex('iDES 8bp', 'Index 23', 'TGGTTCGA', 1);
CALL addIndex('iDES 8bp', 'Index 24', 'CAGTATGG', 1);
CALL addIndex('iDES 8bp', 'Index 25', 'CGTGATTC', 1);
CALL addIndex('iDES 8bp', 'Index 26', 'GGATATCG', 1);
CALL addIndex('iDES 8bp', 'Index 27', 'AGATTGCC', 1);
CALL addIndex('iDES 8bp', 'Index 28', 'CGGAACAA', 1);
CALL addIndex('iDES 8bp', 'Index 29', 'GGTTACAC', 1);
CALL addIndex('iDES 8bp', 'Index 30', 'AAGAGTCG', 1);
CALL addIndex('iDES 8bp', 'Index 31', 'GCTATAGG', 1);
CALL addIndex('iDES 8bp', 'Index 32', 'CCACTAAG', 1);
CALL addIndex('iDES 8bp', 'Index 33', 'ACTCTCTC', 1);

CALL addIndexFamily('SureSelect XT HS', 'ILLUMINA', FALSE);
CALL addIndex('SureSelect XT HS', 'A01', 'GTCTGTCA', 1);
CALL addIndex('SureSelect XT HS', 'B01', 'TGAAGAGA', 1);
CALL addIndex('SureSelect XT HS', 'C01', 'TTCACGCA', 1);
CALL addIndex('SureSelect XT HS', 'D01', 'AACGTGAT', 1);
CALL addIndex('SureSelect XT HS', 'E01', 'ACCACTGT', 1);
CALL addIndex('SureSelect XT HS', 'F01', 'ACCTCCAA', 1);
CALL addIndex('SureSelect XT HS', 'G01', 'ATTGAGGA', 1);
CALL addIndex('SureSelect XT HS', 'H01', 'ACACAGAA', 1);
CALL addIndex('SureSelect XT HS', 'A02', 'GCGAGTAA', 1);
CALL addIndex('SureSelect XT HS', 'B02', 'GTCGTAGA', 1);
CALL addIndex('SureSelect XT HS', 'C02', 'GTGTTCTA', 1);
CALL addIndex('SureSelect XT HS', 'D02', 'TATCAGCA', 1);
CALL addIndex('SureSelect XT HS', 'E02', 'TGGAACAA', 1);
CALL addIndex('SureSelect XT HS', 'F02', 'TGGTGGTA', 1);
CALL addIndex('SureSelect XT HS', 'G02', 'ACTATGCA', 1);
CALL addIndex('SureSelect XT HS', 'H02', 'CCTAATCC', 1);
CALL addIndex('SureSelect XT HS', 'A03', 'AGCAGGAA', 1);
CALL addIndex('SureSelect XT HS', 'B03', 'AGCCATGC', 1);
CALL addIndex('SureSelect XT HS', 'C03', 'TGGCTTCA', 1);
CALL addIndex('SureSelect XT HS', 'D03', 'CATCAAGT', 1);
CALL addIndex('SureSelect XT HS', 'E03', 'CTAAGGTC', 1);
CALL addIndex('SureSelect XT HS', 'F03', 'AGTGGTCA', 1);
CALL addIndex('SureSelect XT HS', 'G03', 'AGATCGCA', 1);
CALL addIndex('SureSelect XT HS', 'H03', 'ATCCTGTA', 1);
CALL addIndex('SureSelect XT HS', 'A04', 'CCGTGAGA', 1);
CALL addIndex('SureSelect XT HS', 'B04', 'GACTAGTA', 1);
CALL addIndex('SureSelect XT HS', 'C04', 'GATAGACA', 1);
CALL addIndex('SureSelect XT HS', 'D04', 'GCTCGGTA', 1);
CALL addIndex('SureSelect XT HS', 'E04', 'GGTGCGAA', 1);
CALL addIndex('SureSelect XT HS', 'F04', 'AACAACCA', 1);
CALL addIndex('SureSelect XT HS', 'G04', 'CGGATTGC', 1);
CALL addIndex('SureSelect XT HS', 'H04', 'AGTCACTA', 1);

CALL addIndexFamily('1D Native Barcodes', 'OXFORDNANOPORE', 0);
CALL addIndex('1D Native Barcodes', 'NB01', 'AAGAAAGTTGTCGGTGTCTTTGTG', 1);
CALL addIndex('1D Native Barcodes', 'NB02', 'TCGATTCCGTTTGTAGTCGTCTGT', 1);
CALL addIndex('1D Native Barcodes', 'NB03', 'GAGTCTTGTGTCCCAGTTACCAGG', 1);
CALL addIndex('1D Native Barcodes', 'NB04', 'TTCGGATTCTATCGTGTTTCCCTA', 1);
CALL addIndex('1D Native Barcodes', 'NB05', 'CTTGTCCAGGGTTTGTGTAACCTT', 1);
CALL addIndex('1D Native Barcodes', 'NB06', 'TTCTCGCAAAGGCAGAAAGTAGTC', 1);
CALL addIndex('1D Native Barcodes', 'NB07', 'GTGTTACCGTGGGAATGAATCCTT', 1);
CALL addIndex('1D Native Barcodes', 'NB08', 'TTCAGGGAACAAACCAAGTTACGT', 1);
CALL addIndex('1D Native Barcodes', 'NB09', 'AACTAGGCACAGCGAGTCTTGGTT', 1);
CALL addIndex('1D Native Barcodes', 'NB10', 'AAGCGTTGAAACCTTTGTCCTCTC', 1);
CALL addIndex('1D Native Barcodes', 'NB11', 'GTTTCATCTATCGGAGGGAATGGA', 1);
CALL addIndex('1D Native Barcodes', 'NB12', 'CAGGTAGAAAGAAGCAGAATCGGA', 1);
-- EndNoTest
