-- StartNoTest
CALL addKitDescriptor('QXT',0,'Agilent',0,'LIBRARY','ILLUMINA',NULL);
CALL addKitDescriptor('KAPA Hyper Prep and Agilent SureSelect XT2', 1, 'Agilent', 1, 'LIBRARY', 'ILLUMINA', 'In-house prep kit');
CALL addKitDescriptor('10X Single Cell RNA', 2,'10X Genomics', 0, 'LIBRARY', 'ILLUMINA', 'Chromium Single Cell 3'' Chip');
CALL addKitDescriptor('PacBio RS II',1,'PacBio',0,'LIBRARY','PACBIO',NULL);
CALL addKitDescriptor('Lexogen SENSE Total RNA',1,'Lexogen',0,'LIBRARY','ILLUMINA',NULL);
CALL addKitDescriptor('KAPA RNA Hyper Prep',1,'KAPA',0,'LIBRARY','ILLUMINA',NULL);
CALL addKitDescriptor('NebNext Ultra II Directional RNA', 1, 'New England BioLabs', 'E7760S', 'LIBRARY', 'ILLUMINA', 'WT Library Prep for Illumina');
CALL addKitDescriptor('10X Genome Linked Reads',2,'10X Genomics','PN-120258','LIBRARY','ILLUMINA','Linked Reads');
CALL addKitDescriptor('GA_PE',0,'GA','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('GA_MP',0,'Illumina','0','LIBRARY','ILLUMINA','GA_MP');
CALL addKitDescriptor('GA_Ready_to_Run',0,'Illumina','0','LIBRARY','ILLUMINA','GA_Ready_to_Run');
CALL addKitDescriptor('GA_Small_RNA',0,'Illumina','0','LIBRARY','ILLUMINA','GA_Small_RNA');
CALL addKitDescriptor('GA_mRNA',0,'Illumina','0','LIBRARY','ILLUMINA','GA_mRNA');
CALL addKitDescriptor('GA_multiplex',0,'GA','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('Agilent SureSelectXT MethylSeq','0','Agilent',0,'LIBRARY','ILLUMINA','Agilent SureSelectXT Human Methyl-Seq targets the most complete content for methylation sequencing, including cancer tissue-specific DMRs, GENCODE promoters, CpG islands, shores and shelves ±4kb, DNaseI hypersensitive sites and RefGenes.');
CALL addKitDescriptor('AmpliSeq Cancer Panel V1',1,'Illumina','0','LIBRARY','ILLUMINA','Ion AmpliSeq Cancer Hotspot Panel V1');
CALL addKitDescriptor('Ion Plus Fragment Library Kit',0,'Illumina','0','LIBRARY','ILLUMINA','Ion Plus Fragment Library Kit');
CALL addKitDescriptor('AmpliSeq-Illumina V1',1,'AmpliSeq','1','LIBRARY','ILLUMINA','AmpliSeq-Illumina Modified Protocol Version 1');
CALL addKitDescriptor('AmpliSeq-KAPA Hyper Prep V1',1,'AmpliSeq','1','LIBRARY','ILLUMINA','Testing');
CALL addKitDescriptor('KAPA BC OnBead',0,'KAPA','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('KAPA Hyper Prep',0,'KAPA','1','LIBRARY','ILLUMINA','KK8504 With KAPA Library Amplification Primer Mix (10X 96 reactions)');
CALL addKitDescriptor('HALO',0,'Illumina','0','LIBRARY','ILLUMINA','HALO');
CALL addKitDescriptor('IDT xGEN Exome Research Panel v1',1,'Illumina','0','LIBRARY','ILLUMINA','IDT xGEN Exome Research Panel v1.');
CALL addKitDescriptor('GA_TruSeq_Library',0,'Illumina','1','LIBRARY','ILLUMINA','TruSeq Genomic Library prep kit');
CALL addKitDescriptor('AmpliSeq-Illumina Exome V1',1,'AmpliSeq','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('Nextera XT',0,'Nextera','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('Thunderbolt Cancer Panel',0,'Thunderbolt','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('Roche SeqCap EZ Exome v3',3,'Roche','0','LIBRARY','ILLUMINA','Roche SeqCap EZ Exome v3.0');
CALL addKitDescriptor('Roche SeqCap Epi CpGiant',0,'Roche','0','LIBRARY','ILLUMINA','The SeqCap Epi CpGiant Enrichment Kits, as part of the SeqCap Epi Enrichment System, enables the targeting of selected genomic regions from bisulfite treated genomic DNA in a single workflow.');
CALL addKitDescriptor('Agilent SureSelect XT',0,'Agilent','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('Agilent SureSelect XT2',0,'Agilent','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('TruSeq Amplicon - Cancer Panel',0,'TruSeq','1','LIBRARY','ILLUMINA','Associated with Illumina PE libraries. Not compatible with the HiSeq - only MiSeq');
CALL addKitDescriptor('TruSeq Methylation Epic Exome',0,'Illumina','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('TruSeq RNA Access',0,'TruSeq','RS-301-2001','LIBRARY','ILLUMINA','RS-301-2001');
CALL addKitDescriptor('KAPA OnBead',0,'KAPA','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('Kapa Hyper Prep Plus',0,'Illumina','0','LIBRARY','ILLUMINA','enzymatic fragmentation');
CALL addKitDescriptor('KAPA Hyper Prep and IDT xGen',5,'KAPA','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('Agilent SureSelect XT Clinical Research',5,'Agilent','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('Agilent SureSelect XT HS',1,'Agilent','1','LIBRARY','ILLUMINA','n/a');
CALL addKitDescriptor('Unspecified',0,'None','None','LIBRARY','ILLUMINA','For libraries with an unknown library kit');
-- EndNoTest
