-- StartNoTest
CALL addTargetedSequencing('ASHPC_0008 Deep Seq','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('Agilent SureSelect All Exon G3362','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('Agilent SureSelect ICGC/Sanger Exon','GSLE Legacy','GA_MP',1);
CALL addTargetedSequencing('Agilent SureSelect ICGC/Sanger Exon','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('Agilent SureSelect ICGC/Sanger Exon','GSLE Legacy','GA_Ready_to_Run',1);
CALL addTargetedSequencing('Agilent SureSelect ICGC/Sanger Exon','GSLE Legacy','GA_Small_RNA',1);
CALL addTargetedSequencing('Agilent SureSelect ICGC/Sanger Exon','GSLE Legacy','GA_mRNA',1);
CALL addTargetedSequencing('Agilent SureSelect ICGC/Sanger Exon','GSLE Legacy','GA_multiplex',1);
CALL addTargetedSequencing('Agilent SureSelectXT MethylSeq', 'TGL', 'Agilent SureSelectXT MethylSeq', 0);
CALL addTargetedSequencing('Agilent SureSelectXT MethylSeq', 'TGL', 'Agilent SureSelectXT MethylSeq', 0);
CALL addTargetedSequencing('Agilent custom see comments','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('Agilent custom see comments','GSLE Legacy','GA_multiplex',1);
CALL addTargetedSequencing('AmpliSeq Cancer Panel v1','GSLE Legacy','AmpliSeq Cancer Panel V1',0);
CALL addTargetedSequencing('AmpliSeq Comprehensive Cancer Panel','GSLE Legacy','Ion Plus Fragment Library Kit',1);
CALL addTargetedSequencing('BART_IAD40521_1','GSLE Legacy','AmpliSeq-Illumina V1', 0);
CALL addTargetedSequencing('BART_IAD40521_23','GSLE Legacy','AmpliSeq-KAPA Hyper Prep V1',0);
CALL addTargetedSequencing('BART_IAD40521_23','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('BART_IAD40521_23','GSLE Legacy','KAPA BC OnBead',1);
CALL addTargetedSequencing('BART_IAD40521_3','GSLE Legacy','AmpliSeq-Illumina V1',0);
CALL addTargetedSequencing('DREAM_IAD60445','GSLE Legacy','AmpliSeq-Illumina V1',0);
CALL addTargetedSequencing('GECCO_IAD82491','GSLE Legacy','KAPA Hyper Prep',1);
CALL addTargetedSequencing('HALO_IBP','GSLE Legacy','HALO',0);
CALL addTargetedSequencing('HALT Agilent  0488571','GSLE Legacy','GA_multiplex',1);
CALL addTargetedSequencing('HALT Agilent 0488571','GSLE Legacy','GA_multiplex',1);
CALL addTargetedSequencing('HaloPlex PCR see comments','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('HaloPlex PCR','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('IDT xGEN Exome Research Panel v1', 'TGL', 'IDT xGEN Exome Research Panel v1', 0);
CALL addTargetedSequencing('Illumina TruSeq Exome','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('Illumina TruSeq Exome','GSLE Legacy','GA_TruSeq_Library',1);
CALL addTargetedSequencing('Ion AmpliSeq Cancer Panel v1','GSLE Legacy','AmpliSeq-KAPA Hyper Prep V1',0);
CALL addTargetedSequencing('Ion AmpliSeq Cancer Panel v1','GSLE Legacy','Ion Plus Fragment Library Kit',1);
CALL addTargetedSequencing('Ion AmpliSeq Exome','GSLE Legacy','AmpliSeq-Illumina Exome V1',1);
CALL addTargetedSequencing('Nextera Rapid Capture Expanded Exome','GSLE Legacy','Nextera XT',0);
CALL addTargetedSequencing('Nimblegen Human Exome v2.0','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('Nimblegen Human Exome v2.0','GSLE Legacy','GA_TruSeq_Library',1);
CALL addTargetedSequencing('Nimblegen ICGC Beta','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('Nimblegen custom see comments','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('Nimblegen custom see comments','GSLE Legacy','GA_TruSeq_Library',1);
CALL addTargetedSequencing('Nimblegen custom see comments','GSLE Legacy','GA_multiplex',1);
CALL addTargetedSequencing('RainDrop BRCA','GSLE Legacy','Thunderbolt Cancer Panel',0);
CALL addTargetedSequencing('Raindance Test (384 Human amp)','GSLE Legacy','GA_multiplex',1);
CALL addTargetedSequencing('Raindance custom see comments','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('Raindance custom see comments','GSLE Legacy','GA_multiplex',1);
CALL addTargetedSequencing('Roche SeqCap EZ Exome v3', '', 'Roche SeqCap EZ Exome v3', 0);
CALL addTargetedSequencing('Roche SeqCap Epi CpGiant', 'TGL', 'Roche SeqCap Epi CpGiant', 0);
CALL addTargetedSequencing('SimSenSeq_JCK2_panel_1','GSLE Legacy','GA_PE',0);
CALL addTargetedSequencing('SureSelect Clinical Research Exome (Cat#: 5190-7338)','GSLE Legacy','Agilent SureSelect XT',0);
CALL addTargetedSequencing('SureSelect Clinical Research Exome (Cat#: 5190-7338)','GSLE Legacy','GA_multiplex',1);
CALL addTargetedSequencing('SureSelect Mouse All Exon', '', 'Agilent SureSelect XT', 0);
CALL addTargetedSequencing('SureSelect v4','GSLE Legacy','Agilent SureSelect XT',1);
CALL addTargetedSequencing('SureSelect v4','GSLE Legacy','Agilent SureSelect XT2',1);
CALL addTargetedSequencing('SureSelect v4','GSLE Legacy','GA_multiplex',1);
CALL addTargetedSequencing('SureSelect v4','GSLE Legacy','KAPA Hyper Prep',1);
CALL addTargetedSequencing('Thunderbolts','GSLE Legacy','Thunderbolt Cancer Panel',0);
CALL addTargetedSequencing('TruSeq Amplicon - Cancer Panel','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('TruSeq Amplicon - Cancer Panel','GSLE Legacy','TruSeq Amplicon - Cancer Panel',0);
CALL addTargetedSequencing('TruSeq Methylation Epic Exome', 'TGL', 'TruSeq Methylation Epic Exome', 0);
CALL addTargetedSequencing('TruSeq RNA Access RS-301-2001','GSLE Legacy','TruSeq RNA Access ',0);
CALL addTargetedSequencing('TruSeq RNA Access', 'TGL', 'TruSeq RNA Access', 0);
CALL addTargetedSequencing('xGen Lockdown AML','GSLE Legacy','GA_PE',1);
CALL addTargetedSequencing('xGen Lockdown AML','GSLE Legacy','KAPA BC OnBead',1);
CALL addTargetedSequencing('xGen Lockdown AML','GSLE Legacy','KAPA Hyper Prep',1);
CALL addTargetedSequencing('xGen Lockdown AML','GSLE Legacy','KAPA OnBead ',1);
CALL addTargetedSequencing('xGen Lockdown AML','GSLE Legacy','Kapa Hyper Prep Plus',1);

CALL addTargetedSequencing('Agilent SureSelect Human All Exon V5', 'Human all exon V5', 'Agilent SureSelect XT2', 0);
CALL addTargetedSequencing('Agilent SureSelect Human All Exon V5', 'Human all exon V5', 'KAPA Hyper Prep', 1);
CALL addTargetedSequencing('Agilent SureSelect Human All Exon V5', 'Human all exon V5', 'QXT', 0);
CALL addTargetedSequencing('Agilent SureSelect Human All Exon V5', 'Human all exon V5', 'KAPA Hyper Prep and Agilent SureSelect XT2', 0);
CALL addTargetedSequencing('Agilent SureSelect Human All Exon V5 + UTRs', 'Human all exon V5 + UTRs', 'KAPA Hyper Prep and Agilent SureSelect XT2', 0);
CALL addTargetedSequencing('Agilent SureSelect Human All Exon V6', 'Human all exon V6', 'KAPA Hyper Prep and Agilent SureSelect XT2', 0);
CALL addTargetedSequencing('Agilent SureSelect Human All Exon V6', 'Human all exon V6', 'QXT', 0);
CALL addTargetedSequencing('Agilent SureSelect Human All Exon V6 Cosmic', 'Human all exon V6 Cosmic', 'KAPA Hyper Prep and Agilent SureSelect XT2', 0);

CALL addTargetedSequencing('Agilent HaloPlex AML', 'Residual Disease Monitoring', 'HALO', 0);
CALL addTargetedSequencing('BLS_targets', 'Combination of HNSC 1-2 and OID44498_hg19_170223 human capture kits for Bratman Lab Sequencing', 'KAPA Hyper Prep and IDT xGen', 0);
call addTargetedSequencing('SureSelect Clinical Research Exome (Cat#: 5190-7338)', 'GSLE Legacy', 'Agilent SureSelect XT Clinical Research', 0);
-- EndNoTest
