/*
 * Copyright (c) 2012. The Genome Analysis Centre, Norwich, UK
 * MISO project contacts: Robert Davey, Mario Caccamo @ TGAC
 * *********************************************************************
 *
 * This file is part of MISO.
 *
 * MISO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MISO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MISO.  If not, see <http://www.gnu.org/licenses/>.
 *
 * *********************************************************************
 */

package uk.ac.bbsrc.tgac.miso.core.service.integration.ws.solid;

import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 */
@WebServiceClient(targetNamespace = "http://solid.aga.appliedbiosystems.com")
public class SolidService extends Service {
  private final static Logger logger = Logger.getLogger(SolidService.class.getName());

  public SolidService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  /**
   * @return returns Solid
   */
  @WebEndpoint(name = "SolidPort")
  public Solid getSolidPort() {
    return super.getPort(new QName("http://solid.aga.appliedbiosystems.com", "SolidPort"), Solid.class);
  }

  /**
   * @param features
   *          A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the
   *          <code>features</code> parameter will have their default values.
   * @return returns Solid
   */
  @WebEndpoint(name = "SolidPort")
  public Solid getSolidPort(WebServiceFeature... features) {
    return super.getPort(new QName("http://solid.aga.appliedbiosystems.com", "SolidPort"), Solid.class, features);
  }
}
